### ISSUE TITLE
Please add some documentation on how to expose these services through an Ingress controller

### ISSUE THREAD

**Issue by jwlogemann** [coreos/kube-prometheus#110]
I'm trying to access these services through an Ingress controller. There's some documentation here: https://github.com/coreos/kube-prometheus/blob/master/docs/exposing-prometheus-alertmanager-grafana-ingress.md on this, but it seems to make no sense at all, and I'm wondering if this is even for Kubernetes at all.

I'm using Kubernetes 1.14, which uses YAML for configuration, not these "jsonnet" files.

**Comment by brancz** [comment]
kube-prometheus is written in jsonnet, which outputs json and is then converted to yaml. Read the documentation to see how you can get started :)

**Comment by llamahunter** [comment]
I was able to follow those instructions to expose the prometheus services via an ingress controller on EKS.  They were pretty clear, tho I did have to adjust them slightly to work with the aws-alb-ingress-controller (extra annotations, mainly).
