### ISSUE TITLE
kubernetes-mixin and K8S 1.14 metrics overhaul

### ISSUE THREAD

**Issue by bgagnon** [coreos/kube-prometheus#111]
The dependency on `kubernetes-monitoring/kubernetes-mixin` is currently locked on `release-0.1`. According to the README on that repo, newer versions of the library will require Kubernetes 1.14+ due to the major metrics overhaul that happened in this release.

What can we expect from the `kube-prometheus` side of things? Will it also begin requiring 1.14+?

**Comment by brancz** [comment]
As mentioned in the [release notes of v0.1.0](https://github.com/coreos/kube-prometheus/releases/tag/v0.1.0), the release-0.1 release series will continue to be compatible with 1.13, but master will be 1.14+ only going forward.

**Comment by bgagnon** [comment]
Thanks!
