### ISSUE TITLE
Wrong labels used for Kube-scheduler and Kube-controller-manager discovery.

### ISSUE THREAD

**Issue by jeanluclariviere** [coreos/kube-prometheus#112]
**What happened?**
KubeControllerManagerDown and KubeSchedulerDown alerts are firing after a clean install of kube-prometheus on a bare-metal cluster.

**Did you expect to see some different?**
I expected both to be discovered and up.

**How to reproduce it (as minimally and precisely as possible)**:
Apply the default manifests on a new bare-metal cluster.

**Environment**

* Prometheus Operator version:
quay.io/coreos/prometheus-operator:v0.30.0

* Kubernetes version information:

    `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    kubeadm

* Manifests:
n/a

* Prometheus Operator Logs:
n/a

* Prometheus Logs:
n/a

**Anything else we need to know?**:
After reviewing the pods / services for both kube-scheduler and controller-manager, i determined that the wrong label selector was being used. Both kube-scheduler and controller-manager are using the "component:" label, and the discovery services for each of these are using the "k8s-app:" label. Updating the services to use the correct label resolved this issue.

Edit: I am importing the kubeadm cluster creation tool in my jsonnet as well.
```(import 'kube-prometheus/kube-prometheus-kubeadm.libsonnet')```

**Comment by brancz** [comment]
So you're saying https://github.com/coreos/kube-prometheus/blob/master/jsonnet/kube-prometheus/kube-prometheus-kubeadm.libsonnet is not doing the trick for you?

**Comment by jeanluclariviere** [comment]
> So you're saying https://github.com/coreos/kube-prometheus/blob/master/jsonnet/kube-prometheus/kube-prometheus-kubeadm.libsonnet is not doing the trick for you?

It seems that "k8s-app" is no longer the label being used. I've deployed all of clusters (currently 1.14.1) using kubeadm and the label for both kube-scheduler and kube-controller-manager is "component"

**Comment by brancz** [comment]
Yes, [here it changes it for the controller manager](https://github.com/coreos/kube-prometheus/blob/50d3e774a57a2b6c2838cfc26d29dfe9a197ffb4/jsonnet/kube-prometheus/kube-prometheus-kubeadm.libsonnet#L8) and [here for the scheduler](https://github.com/coreos/kube-prometheus/blob/50d3e774a57a2b6c2838cfc26d29dfe9a197ffb4/jsonnet/kube-prometheus/kube-prometheus-kubeadm.libsonnet#L13).

**Comment by jeanluclariviere** [comment]
Thanks for confirming - so your first statement was in fact correct. Could I have imported it incorrectly?

Here is what i'm building:

```
local k = import 'ksonnet/ksonnet.beta.3/k.libsonnet';
local pvc = k.core.v1.persistentVolumeClaim;

local kp =
  (import 'jsonnet/kube-prometheus/kube-prometheus.libsonnet') +
  (import 'kube-prometheus/kube-prometheus-kubeadm.libsonnet') +
  (import 'kube-prometheus/kube-prometheus-node-ports.libsonnet') +
  (import 'kube-prometheus/kube-prometheus-anti-affinity.libsonnet') +
  (import 'jsonnet/kube-prometheus/kube-prometheus-bootkube.libsonnet') +
  {
    _config+:: {
      namespace: 'monitoring',
    },
    prometheus+:: {
      prometheus+: {
        spec+: {
          retention: '15d',
          storage: {
            volumeClaimTemplate:
              pvc.new() +
              pvc.mixin.spec.withAccessModes('ReadWriteOnce') +
              pvc.mixin.spec.resources.withRequests({ storage: '20Gi' }) +
              pvc.mixin.spec.withStorageClassName('rook-ceph-block'),

          },  // storage
        },  // spec
      },  // prometheus
    },  // prometheus

  };
{ ['0prometheus-operator-' + name]: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) }
```

**Comment by brancz** [comment]
You want to remove the bootkube line. Then it should work.

**Comment by jeanluclariviere** [comment]
Of course, how daft of me. Removing it solved my problem, sorry for the trouble.

**Comment by brancz** [comment]
No problem, happy we could resolve it :)
