### ISSUE TITLE
KubeCPUOvercommit alert not right

### ISSUE THREAD

**Issue by zgfh** [coreos/kube-prometheus#113]
**What happened?**
KubeCPUOvercommit alert not right
```
sum(namespace_name:kube_pod_container_resource_requests_cpu_cores:sum)
  / sum(node:node_num_cpu:sum) > (count(node:node_num_cpu:sum) - 1) / count(node:node_num_cpu:sum)
```
node:node_num_cpu:sum should use node allocatable memory from kubelet

**Comment by brancz** [comment]
You're absolutely right. Would you like to fix this in the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin)? That's where we get this alert from, it's just a dependency of kube-prometheus :slightly_smiling_face: .

**Comment by zgfh** [comment]
sorry reply late
PR: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/216/files

**Comment by zgfh** [comment]
@brancz and dashboard :https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/217

**Comment by zgfh** [comment]
@brancz thanks to merge.
want should I do to update dependency of kube-prometheus ?

**Comment by brancz** [comment]
See this guide: https://github.com/coreos/kube-prometheus#contributing

**Comment by zgfh** [comment]
I mean should I update kubernetes-mixin version to master ? https://github.com/coreos/kube-prometheus/blob/master/jsonnet/kube-prometheus/jsonnetfile.json#L21
Or  create a PR for release-0.1 of  kubernetes-mixin ?

**Comment by gokhansengun** [comment]
FWIW, this PR to this issue is also fixing an issue where the alarm is always firing in a single-node k8s cluster. It is because `count(node:node_num_cpu:sum)` is always 1 and the comparison is made against 0 ;)

**Comment by brancz** [comment]
sorry I misunderstood, master :)

**Comment by zgfh** [comment]
close this, because https://github.com/coreos/kube-prometheus/pull/133 have fixed it
