### ISSUE TITLE
Not getting any data in Grafana

### ISSUE THREAD

**Issue by james-knott** [coreos/kube-prometheus#116]
**What did you do?**

Installed via the quickstart in AKS

**Did you expect to see some different?**

All the pods came up normally after running the create then apply command on the manifest folder.

**Environment**
K8s in AKS 1.13

Not getting any data on any of the default graphs

**Comment by brancz** [comment]
Could you check whether metrics are successfully collected by checking the `/targets` page on the Prometheus UI?

**Comment by james-knott** [comment]
kubectl --namespace monitoring port-forward svc/prometheus-k8s 9090

No page can be displayed. That would be a problem :)

**Comment by james-knott** [comment]
Kubernetes / Use Method / Cluster and Kubernetes / Use Method / Pods - both work but none of the other graphs work

**Comment by brancz** [comment]
The kubelet targets are where most of the dashboards data comes from. What’s the error the UI is saying?
