### ISSUE TITLE
`make generate` produces stale manifests

### ISSUE THREAD

**Issue by paulfantom** [coreos/kube-prometheus#125]
**What happened?**
I ran `make generate` and got stale `manifests/` from commit `fa9350694108ac3b6cb7aeef57b28320e187eef6`
Same is happening for [`make generate-in-docker` used by CI](https://github.com/coreos/kube-prometheus/blob/master/.travis.yml#L19)

**Did you expect to see some different?**
I wanted to have manifests generated from `jsonnet/` directory.

**How to reproduce it (as minimally and precisely as possible)**:
Change something in `jsonnet/` dir and run `make generate`.

**Anything else we need to know?**:

This is happening due to `make generate` installing previous version of `kube-prometheus` in `vendor/` directory. Due to this **CI tests are unreliable**.

It is happening because we are using locked kube-prometheus version in `jsonnetfile.lock.json`.

Issue was also mentioned here: https://github.com/coreos/kube-prometheus/pull/119#issuecomment-501363650

/cc @metalmatze

**Comment by metalmatze** [comment]
This is something we need to fix upstream in jsonnet-bundler. I have started working on this and actually have it in my sprint too.
I'll just need to find time to do it! Sorry.

https://github.com/jsonnet-bundler/jsonnet-bundler/issues/8
