### ISSUE TITLE
Inconsistent collector.filesystem.ignored-fs-types values

### ISSUE THREAD

**Issue by huanggze** [coreos/kube-prometheus#131]
**What did you do?**

When checking node-exporter-daemonset yaml with node-exporter filesystem collector source code (both on master branch), I found inconsistent flag values for `collector.filesystem.ignored-fs-types`.

For [`kube-prometheus/manifests/node-exporter-daemonset.yaml`](https://github.com/coreos/kube-prometheus/blob/master/manifests/node-exporter-daemonset.yaml), it is:
```
- --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
```
For the [source code](https://github.com/prometheus/node_exporter/blob/master/collector/filesystem_linux.go#L33), it is:
```
defIgnoredFSTypes     = "^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$"
```

Obviously, the gap is, like `squashfs` (might be used in loopback devices).

Can you provide more info why we don't use default value as the source code here?

**Comment by brancz** [comment]
This was originally done because an old version of node-exporter did this differently until this became the default. I think we're at a point where we can just go with the default.
