### ISSUE TITLE
Duplicate records in prometheus-rules

### ISSUE THREAD

**Issue by chiefy** [coreos/kube-prometheus#134]
There's duplicate records for `namespace:container_cpu_usage_seconds_total:sum_rate` and `namespace:container_memory_usage_bytes:sum` here: https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-rules.yaml#L15-L30

**Comment by brancz** [comment]
Thanks for reporting! This is actually pulled in through the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) dependency, we're gonna need to fix it there. Can you open an issue there? :) 

RE: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/rules/rules.libsonnet

**Comment by brancz** [comment]
cc @metalmatze

**Comment by metalmatze** [comment]
Interesting. We should discuss upstream, if we need both (as the might be different) or can get rid of one after the Kubernetes metrics overhaul.
Let's discuss there.

**Comment by simonpasquier** [comment]
I've filed https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/230 to follow up.

**Comment by BenoitKnecht** [comment]
This was fixed in kubernetes-monitoring/kubernetes-mixin#230, and kube-prometheus now depends on kubernetes-monitoring/kubernetes-mixin@15ddfa20a6921ffbd43172eb54f6bdc1bcf8d3d3, which includes the fix (kubernetes-monitoring/kubernetes-mixin@32c7960c8facc1e6a981587b5972050fe8bd11bf).

**Comment by brancz** [comment]
Thanks @BenoitKnecht !
