### ISSUE TITLE
Errors of 'uable to recognize xxxx'

### ISSUE THREAD

**Issue by Kiddinglife** [coreos/kube-prometheus#135]
I typed kubectl create -f manifests/ and then got a lot of errors:

unable to recognize "manifests/0prometheus-operator-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/alertmanager-alertmanager.yaml": no matches for kind "Alertmanager" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/alertmanager-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/grafana-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/kube-state-metrics-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/node-exporter-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

**Comment by brancz** [comment]
Please read the quickstart guide: https://github.com/coreos/kube-prometheus#quickstart

The comments explain what's happening. This is somewhat expected.
