### ISSUE TITLE
Missing node metrics

### ISSUE THREAD

**Issue by BostjanBozic** [coreos/kube-prometheus#136]
**What did you do?**
I have deployed monitoring stack using `prometheus-operator` with provided manifests. Request/limits  are exported as required, but node/pod metrics metrics are missing.
I checked logs all around and it seems only `addon-resizer` container in `kube-state-metrics` pod is failing.

What is interesting is that with `kubectl top pods`, I get the metrics, but I do not see them in Prometheus. At the same time `kubectl top nodes` returns no metrics what-so-ever.

**Did you expect to see some different?**
I expected to see node/pod metrics.

**Environment**
RHEL 7.3

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.31.0`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

    `kubeadm`

* Manifests:

Provided manifests in `coreos/kube-prometheus` repo

* Kube-state-metrics kube-state-metrics container Logs:
   
```
I0701 12:41:48.286804       1 main.go:80] Using default collectors
I0701 12:41:48.376129       1 main.go:88] Using all namespace
I0701 12:41:48.376152       1 main.go:124] metric white-blacklisting: blacklisting the following items:
W0701 12:41:48.376253       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0701 12:41:48.378835       1 main.go:166] Testing communication with server
I0701 12:41:48.580860       1 main.go:171] Running with Kubernetes cluster version: v1.13. git version: v1.13.1. git tree state: clean. commit: eec55b9ba98609a46fee712359c7b5b365bdd920. platform: linux/amd64
I0701 12:41:48.580946       1 main.go:173] Communication with server successful
I0701 12:41:48.581639       1 main.go:182] Starting kube-state-metrics self metrics server: 127.0.0.1:8082
I0701 12:41:48.676146       1 builder.go:112] Active collectors: configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,jobs,limitranges,namespaces,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets
I0701 12:41:48.676234       1 main.go:208] Starting metrics server: 127.0.0.1:8081
```

* Kube-state-metrics addon-resizer container Logs:
   
```
ERROR: logging before flag.Parse: I0701 12:41:49.179488       1 pod_nanny.go:65] Invoked by [/pod_nanny --container=kube-state-metrics --cpu=100m --extra-cpu=2m --memory=150Mi --extra-memory=30Mi --threshold=5 --deployment=kube-state-metrics]
ERROR: logging before flag.Parse: I0701 12:41:49.179659       1 pod_nanny.go:81] Watching namespace: monitoring, pod: kube-state-metrics-6986bdc58b-fljlp, container: kube-state-metrics.
ERROR: logging before flag.Parse: I0701 12:41:49.179669       1 pod_nanny.go:82] storage: MISSING, extra_storage: 0Gi
ERROR: logging before flag.Parse: I0701 12:41:49.277142       1 pod_nanny.go:171] Failed to read data from config file "MISSING/NannyConfiguration": open MISSING/NannyConfiguration: no such file or directory, using default parameters
ERROR: logging before flag.Parse: I0701 12:41:49.277239       1 pod_nanny.go:109] cpu: 100m, extra_cpu: 2m, memory: 150Mi, extra_memory: 30Mi
ERROR: logging before flag.Parse: I0701 12:41:49.277271       1 pod_nanny.go:138] Resources: [{Base:{i:{value:100 scale:-3} d:{Dec:<nil>} s:100m Format:DecimalSI} ExtraPerNode:{i:{value:2 scale:-3} d:{Dec:<nil>} s:2m Format:DecimalSI} Name:cpu} {Base:{i:{value:157286400 scale:0} d:{Dec:<nil>} s:150Mi Format:BinarySI} ExtraPerNode:{i:{value:31457280 scale:0} d:{Dec:<nil>} s:30Mi Format:BinarySI} Name:memory}]
```

**Anything else we need to know?**:
I have checked [kube-state-metrics issue #706](https://github.com/kubernetes/kube-state-metrics/issues/706), thinking `addon-resizer` might be to blame, but this not resolve the issue.

**Comment by brancz** [comment]
The prometheus adapter does require the kube-state-metrics metrics, so this seems plausible. Can you check that these metrics individually return something? (leave out the templating bits)

* https://github.com/coreos/kube-prometheus/blob/026c09e6ad6911a76a1e0da07400d055beb8a51a/manifests/prometheus-adapter-configMap.yaml#L7
* https://github.com/coreos/kube-prometheus/blob/026c09e6ad6911a76a1e0da07400d055beb8a51a/manifests/prometheus-adapter-configMap.yaml#L19

**Comment by BostjanBozic** [comment]
@brancz thank you for feedback.

I tried to run those queries on Prometheus instance and they do not return anything. It seems that only metrics that are available are fetched from configurations (e.g. `resources.limits.cpu`)

**Comment by brancz** [comment]
Can you check the `/targets` page in the Prometheus UI as well as the alerts that are firing? This might be the node-exporter not being scraped successfully.

**Comment by BostjanBozic** [comment]
Cheers for pointing me in right direction, issue was that I set up node exporter `--secure-listen-address` to 9101, but forgot to update container port.

It seems you actually helped me before with this issue [prometheus-operator #2021](https://github.com/coreos/prometheus-operator/issues/2021), but it got out of my mind. Sorry for doubling the effort...
