### ISSUE TITLE
use helm install 

### ISSUE THREAD

**Issue by light2cloud** [coreos/kube-prometheus#171]
So can I install kube-prometheus using the helm tools?What should I do if I can?

**Comment by brancz** [comment]
There is a helm chart but we don’t use nor maintain it. For the better or worse it’s called Prometheus operator on the upstream stable charts.

**Comment by yuswift** [comment]
Is there any support for installing kube-prometheus with helm? Only found charts with prometheus operator :)

**Comment by paulfantom** [comment]
> Is there any support for installing kube-prometheus with helm

As Frederic said - we don't use nor maintain any helm charts. So no, there is no support.
