### ISSUE TITLE
Updating documentation to clarify externalUrl difference for Grafana

### ISSUE THREAD

**Issue by lanmarti** [coreos/kube-prometheus#199]
**What is missing?**
The [documentation on exposing the Prometheus/Grafana/Alertmanager dashboards](https://github.com/coreos/kube-prometheus/blob/master/docs/exposing-prometheus-alertmanager-grafana-ingress.md) is a bit vague about setting the external URL for Grafana, or more specifically, does not mention that this happens in a slightly different way than the Prometheus/Alertmanager approach. 

**Why do we need it?**
For people familiar with the CRDs for Prometheus and Alertmanager this might be immediately clear, but as a newcomer to this operator and jsonnet, I wasted a bit of time figuring out what I was doing wrong. By referencing this directly in the documentation, others might avoid the same pitfall.

**Environment**
Not applicable

* kube-prometheus version:
Not applicable

**Anything else we need to know?**:
I'll create a PR that updates the documentation, making a clear mention of the difference.

**Comment by LiliC** [comment]
I think since the PR was merged, we can close this now. Thanks for your contribution! :)
