### ISSUE TITLE
Support for Thanos 0.6.x

### ISSUE THREAD

**Issue by andrew-chattermill** [coreos/kube-prometheus#206]
Currently trying to make it work with Thanos 0.6.0.

I could see a [commit](https://github.com/coreos/kube-prometheus/commit/f1cd88fdbb2c7019f09e36f1160a1e692ca16aaf) that removes all the components of the Thanos except for Thanos sidecar. 
Where is it planned to manage jsonnet files for other Thanos components?

**Comment by yeya24** [comment]
You can take a look at https://github.com/metalmatze/kube-thanos 😄
