### ISSUE TITLE
Mounting command: systemd-run Mounting arguments

### ISSUE THREAD

**Issue by huisebug** [coreos/kube-prometheus#211]
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/1789c6b1-cfc7-11e9-b56c-00163e02d405/volumes/kubernetes.io~nfs/pvc-c9eb5a05-cf7e-11e9-b56c-00163e02d405 --scope -- mount -t nfs **:/nfs-storageClass/monitoring-prometheus-k8s-db-prometheus-k8s-0-pvc-c9eb5a05-cf7e-11e9-b56c-00163e02d405 /var/lib/kubelet/pods/1789c6b1-cfc7-11e9-b56c-00163e02d405/volumes/kubernetes.io~nfs/pvc-c9eb5a05-cf7e-11e9-b56c-00163e02d405
Output: Running scope as unit run-27974.scope.
mount.nfs: access denied by server while mounting 9fa464a0e1-wpr17.cn-zhangjiakou.nas.aliyuncs.com:/nfs-storageClass/monitoring-prometheus-k8s-db-prometheus-k8s-0-pvc-c9eb5a05-cf7e-11e9-b56c-00163e02d405

**Comment by LiliC** [comment]
@huisebug can you explain your problem you are facing, bit hard to decrypt the above.

**Comment by huisebug** [comment]
I used the chart to build nfs-client-provisioner, you can manually create pvc, and successfully set up dynamic pv, but the combination of prometheus will prompt the above error. @LiliC

**Comment by brancz** [comment]
We neither use nor maintain the helm chart, please open an issue on the upstream helm charts repo.
