### ISSUE TITLE
Quickstart on AKS : node(s) didn't match node selector and pods "prometheus-adapter-xxxxxx-" is forbidden

### ISSUE THREAD

**Issue by dparkar** [coreos/kube-prometheus#213]
**What did you do?**
Clone the git repo, ran through Quickstart to install the monitoring stack on a k8s cluster in AKS.

**Did you expect to see some different?**
Yes, functioning stack.

**Environment**
Azure Kubernetes Service with Kubernetes version 1.12.8

* Prometheus Operator version:
quay.io/coreos/prometheus-operator:v0.32.0

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:
Azure Kubernetes Service

* Manifests:

All

* Prometheus Operator Logs:

kubectl logs prometheus-operator-XXXX-XXXX --namespace monitoring
(returns empty)

* Prometheus Logs:

NA

**Anything else we need to know?**:
First time user of this stack on K8s

I posted on kubernetes slack channel and was suggested to switch out the [now deprecated node selector](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#beta-kubernetes-io-os-deprecated) used in [prometheus operator deployment](https://github.com/coreos/kube-prometheus/blob/master/manifests/0prometheus-operator-deployment.yaml#L43) and [grafana deployment](https://github.com/coreos/kube-prometheus/blob/master/manifests/grafana-deployment.yaml#L100). But even after switching to "kubernetes.io/os", its same error and nodes stay in pending state.

Note that I can connect to grafana but cannot connect to prometheus or alert-manager. 
Error : unable to forward port because pod is not running. Current status=Pending
When I see the pods in k8s dashboard the are all in pending state with error : 
0/X nodes are available: X node(s) didn't match node selector.

Removed the node selector from all manifests and the deployments went through. But the pods are in a crash loop. The error seems to be found in replicaset-controllers : 

**pods "prometheus-adapter-xxxxxx-" is forbidden: error looking up service account monitoring/prometheus-adapter: serviceaccount "prometheus-adapter" not found**

![image](https://user-images.githubusercontent.com/208161/64497252-5159a180-d261-11e9-9a9e-94941937e5a3.png)

Appreciate the guidance.

**Comment by brancz** [comment]
For versions before Kubernetes v1.14.0 you need to use the `release-0.1` branch instead of master. Did you do that?

**Comment by dparkar** [comment]
thanks ! that was it. should we add that to the documentation ? (or am I missing it somewhere)

**Comment by brancz** [comment]
Yeah if you could add a note somewhere where you would have expected it? That would be awesome! :)

**Comment by dparkar** [comment]
PR : https://github.com/coreos/kube-prometheus/pull/230
