### ISSUE TITLE
grafana-dashboardDefinitions.yaml Node-rsrc-use.json data error

### ISSUE THREAD

**Issue by wsxedcer** [coreos/kube-prometheus#217]
version： master

grafana-dashboardDefinitions.yaml  File line 11914 error

`"expr": "1 -\n(\n  max without (mountpoint, fstype) (node_filesystem_avail_bytes{job=\"node-exporter\", , instance=\"$instance\"}})\n/\n  max without (mountpoint, fstype) (node_filesystem_size_
      bytes{job=\"node-exporter\", , instance=\"$instance\"}})\n)\n",`

After logging in to the web page of grafana, USE Method/Node -->Disk Space Utilisation  prompt “parse error at line 3, char 87: unexpected "," in label matching, expected identifier
”   

The correct one should be
`"expr": "1 -\n(\n  max without (mountpoint, fstype) (node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"$instance\"})\n/\n  max without (mountpoint, fstype) (node_filesystem_size_byt
      es{job=\"node-exporter\", instance=\"$instance\"})\n)\n"`

**Comment by brancz** [comment]
This query is defined in the node-mixin: https://github.com/prometheus/node_exporter/tree/master/docs/node-mixin

Could you fix it there and update our dependency here? :slightly_smiling_face:

**Comment by wsxedcer** [comment]
I don't know how to convert it. I queried the source code of node-mixin/dashboards/use.libsonnet  and found another parameter in the middle of the code.
https://github.com/prometheus/node_exporter/blob/master/docs/node-mixin/dashboards/use.libsonnet
file line  156/283/285

**Comment by wu0407** [comment]
this comiit like fixed.
https://github.com/coreos/kube-prometheus/commit/6a11f9c3bcaf173f5a37fe4351d8b164b914c5de#diff-a01fecea8d176247363af6ef3afd72c6

**Comment by brancz** [comment]
Thanks @wu0407. In that case closing this.
