### ISSUE TITLE
grafana Display problem

### ISSUE THREAD

**Issue by huisebug** [coreos/kube-prometheus#218]
![image](https://user-images.githubusercontent.com/27762438/64759543-faf2a880-d569-11e9-983f-0bb5fb363ac9.png)

![image](https://user-images.githubusercontent.com/27762438/64759555-08a82e00-d56a-11e9-9f7c-12d1a18d3eef.png)

Grafana's display, I found that there are two data sources, one is prometheus, one default, default I found is the configmap mounted by grafana, now the display of grafana is not displayed, I need to manually switch the data source to default to display
I want to know how to solve this problem, and I want to know how these configmaps are generated.

**Comment by metalmatze** [comment]
These ConfigMaps containing the dashboards are generated with jsonnet. Most (if not all) of them are actually part of the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) project.
