### ISSUE TITLE
Memory Saturation (Swapped Pages) based on paging instead of swapping

### ISSUE THREAD

**Issue by zaphod42** [coreos/kube-prometheus#222]
**What happened?**

I looked at the Memory Saturation graph for a cluster/node that does not have any swap and noticed the graph indicated that swap was happening. `vmstat 1` on a node confirmed that there is no `si` or `so` activity.

**Did you expect to see some different?**

I expected to see the graph only every showing 0 as no swap activity is possible on the nodes.

**How to reproduce it (as minimally and precisely as possible)**:

Create a node without swap. You may have to create a pod that actively uses mmapped files, which will create paging activity. Look at the graph and it will show the paging activity as swap.

**Environment**

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.32.0`
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:56:40Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`
    

**Anything else we need to know?**:

I know that this isn't defined in this project, but I got tired of trying to track down where it came from.

**Comment by brancz** [comment]
It's defined in the node-mixin https://github.com/prometheus/node_exporter/tree/master/docs/node-mixin
