### ISSUE TITLE
Error in statefulset json

### ISSUE THREAD

**Issue by tomerleib** [coreos/kube-prometheus#237]
**What happened?**
New installation of kube-prometheus using the prometheus-operator chart.
When checking the dashboard for stateful set, there is the following error:
```
Templating init failed: parse error at char 63: could not parse remaining input ", cluster=\"\""...
```
**Did you expect to see some different?**
I've imported dashboard 5330 and it works fine so I guess this should work the same.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.32.0`
    

* Kubernetes version information:

    `Server Version: v1.14.6-eks-5047ed`
    

* Kubernetes cluster kind:

EKS 
* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
We neither use nor maintain the helm charts. Please open an issue on the helm charts repo.

**Comment by tomerleib** [comment]
I'm sorry, but this is irrelevant to how it was deployed since the problem is with the code in `grafana-dashboardDefinitions.yaml` from here.
For some reason, it failed to render the `cluster` variable so it failed on lines such as:
`{job=\"kubelet\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$statefulset.*\"}`.
If I change this to this:
`{namespace=\"$statefulset_namespace\",pod_name=~\"$statefulset_name.*\"}` it works fine without errors.
