### ISSUE TITLE
No kind "Prometheus" is registered

### ISSUE THREAD

**Issue by genti-t** [coreos/kube-prometheus#24]
I'm trying to deploy prometheus using the manifests on this repo.

the TPRs are created
```
alertmanager.monitoring.coreos.com      Managed Alertmanager cluster          v1alpha1
prometheus.monitoring.coreos.com        Managed Prometheus server             v1alpha1
service-monitor.monitoring.coreos.com   Prometheus monitoring for a service   v1alpha1
```

but when I try to apply manifests/prometheus/prometheus-k8s.yaml :
```
 no kind "Prometheus" is registered for version "monitoring.coreos.com/v1alpha1"
```

the same goes for:
```
error: unable to decode "manifests/alertmanager/alertmanager.yaml": no kind "Alertmanager" is registered for version "
```

Can someone address me how to figure it  out why this is happening ?

**Comment by brancz** [comment]
This error is relatively arbitrary, if you change the the `kubectl apply ...` to `kubectl create ...` it works. I will update the `hack/` scripts as a follow-up of this. Thanks for reporting!

**Comment by brancz** [comment]
This only happens with a client and server version of `>=1.5.0`. Be aware that there is currently a problem with `emptyDir` volumes as described [here](https://github.com/coreos/prometheus-operator/issues/74).

Out of curiosity, do you have a working Persistent Volume provisioner for your cluster?

**Comment by genti-t** [comment]
Thank you @brancz 
I have a new fresh cluster v.1.5.1. I have not tried any use for Persistent Volume on this version yet.

**Comment by brancz** [comment]
In which environment if I may ask? GCE, AWS, base-metal? Is there a chance that you will have a PV Provisioner?

**Comment by genti-t** [comment]
bare-metal and vagrant for now, and yes I am planing to use Persistent Volume provisioner

**Comment by brancz** [comment]
We would greatly appreciate your help if you have it set up. Collecting reports in https://github.com/coreos/prometheus-operator/pull/75. Thanks and happy holidays 🙂

**Comment by brancz** [comment]
Was the initial problem solved by not using `apply` @genti-t ? If so I think we can close this issue.

**Comment by chancez** [comment]
I also saw this when running `kubectl apply`. It might be worth adding some comments into `hack/cluster-monitoring` scripts indicating why you use `kubectl create` and not `kubectl apply`. 

I imagine a few people (including myself) are running the script once, potentially tweaking settings (node ports, for example), thinking they can change it to `kubectl apply` so they can more easily edit and change things, and then running into this issue. The error is really not obvious either so it makes it seem like it's an issue with the manifests/operator, rather than kubectl.

**Comment by genti-t** [comment]
@brancz not using apply, the problem is solved. You can can close this issue.
Thank you

**Comment by brancz** [comment]
Thanks for the feedback! I will add some comments and use apply on those where it works as a follow up @chancez

**Comment by brancz** [comment]
Closing here as #27 has been merged.
