### ISSUE TITLE
Is it possible to import prometheus rules from file and keep generating the default rules?

### ISSUE THREAD

**Issue by gdamberg** [coreos/kube-prometheus#243]
**What did you do?**
Trying to import our own prometheus rules in addition to the default rules. Trying out the examples given in the examples folder

```
# generate using a json file with rule definitions
mkdir rendered
jsonnet -J vendor -m rendered "prometheus-additional-rendered-rule-example.jsonnet" | xargs -I{} sh -c 'cat {} | gojsontoyaml > {}.yaml; rm -f {}' -- {}

# generate using rule definitions inlined in the jsonnet file
mkdir inline
jsonnet -J vendor -m inline "prometheus-additional-alert-rule-example.jsonnet" | xargs -I{} sh -c 'cat {} | gojsontoyaml > {}.yaml; rm -f {}' -- {}


# diff the result
diff rendered/prometheus-rules.yaml inline/prometheus-rules.yaml
```
**Did you expect to see some different?**

I expected the two resulting prometheus-rules.yaml files to be more or less identical. 

Instead the rendered example (using import) **only** contains the rules defined in the examples.json file, while the example with the rules inlined in the jsonnet file results in all the default rules in addition to the configured rule.

Is it possible to have an import and still get the default rules? My (admittedly shallow) jsonnet skills have not managed to solve this...

**Environment**
* kube-prometheus at master
* jsonnet
`Jsonnet commandline interpreter v0.14.0`

**Anything else we need to know?**:

**Comment by brancz** [comment]
You're right, there are some mistakes in these jsonnet files. I just fixed them locally, and will open a PR soon. Sorry for the inconvenience!

**Comment by brancz** [comment]
This should be fixed with the changes in https://github.com/coreos/kube-prometheus/pull/244.

**Comment by gdamberg** [comment]
Looks so obvious when I look at the solution :-)

Thanks for quick reply and fix!
