### ISSUE TITLE
node-exporter's rbac proxy resources are not configurable and not stripped by mixin

### ISSUE THREAD

**Issue by bgagnon** [coreos/kube-prometheus#255]
The main `node-exporter` container is correct, but its `kube-rbac-proxy` is still using hardcoded values. This looks like an oversight on my part when I provided the mixin solution #132 for #72.

```jsonnet
        container.mixin.resources.withRequests({ cpu: '10m', memory: '20Mi' }) +
        container.mixin.resources.withLimits({ cpu: '20m', memory: '60Mi' }) +
```

Other components using `kube-rbac-proxy` sidecar have been fixed and share the same limits, so I think the same solution should apply here.

**Comment by dimm0** [comment]
How about the grafana limits? Could those be stripped too?

**Comment by BenoitKnecht** [comment]
I hadn't noticed this issue before submitting #279, but it has been merged now so this issue should be fixed now.
