### ISSUE TITLE
the configure of Alertmanager is not work

### ISSUE THREAD

**Issue by xcjing** [coreos/kube-prometheus#266]
**I have installed the kube-prometheus for my K8S by kubectl apply -f  /kube-prometheus/manifests  and it's work. now I want to configure the AlertManager to send alert mail, but failed, it's seem the  configure of Alertmanager is not work**

**Environment**

**below is my environment**
[root@webserver3 ~]# docker images -a|grep prome
quay.io/coreos/prometheus-config-reloader     v0.33.0             2d95323c37d6        5 weeks ago         17.6MB
quay.io/coreos/prometheus-operator            v0.33.0             b4f609ce281e        5 weeks ago         42.1MB
quay.io/prometheus/prometheus                 v2.11.0             b97ed892eb23        3 months ago        126MB
quay.io/prometheus/alertmanager               v0.18.0             ce3c87f17369        3 months ago        51.9MB
quay.io/prometheus/node-exporter              v0.18.1             e5a616e4b9cf        4 months ago        22.9MB
quay.io/coreos/k8s-prometheus-adapter-amd64   v0.4.1              9dcf4b7170ef        10 months ago       60.7MB

    

* Kubernetes version information:

    `kubectl version`
    1.15.3 

* Kubernetes cluster kind:

    I install my k8s by kubeadm

* Manifests:

**below is my alertmanager-config.yaml.**

apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp@qq.com:465'
      smtp_from: 'xxxxxx@qq.com'
      smtp_auth_username: 'xxxxxx@qq.com'
      smtp_auth_password: 'lhhbntarlhckcagb'
      smtp_require_tls: false
      smtp_hello: 'qq.com'

    receivers:
    - name: default-receiver
      email_configs:
      - to: "xxxxxxxxx@yeah.net"
      send_resolved: true

    route:
      group_interval: 1m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 1m

 I execute: **kubectl apply -f alertmanager-config.yaml** to config it and it success. but in AlertManager web UI the config not change.  the config in: http://132.145.80.199:30093/#/status
is still the default as below:  you can access http://132.145.80.199:30093/#/status to have a look.

Config
global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: "null"
  group_by:
  - job
  routes:
  - receiver: "null"
    match:
      alertname: Watchdog
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: "null"
templates: []

**I want to copy the alertmanager.yaml to docker image's /etc/alertmanager/config/alertmanager.yaml  to reload it by access in my browser: http://132.145.80.199:30093/-/reload, but I got error:  Method Not Allowed**
please help me on how to config alertmanager unnder k8s.

* Prometheus Operator Logs:

```
Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by xcjing** [comment]
**my Prometheus Operator Logs:**
level=warn ts=2019-10-18T05:33:33.587Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 98945 (99036)"
level=warn ts=2019-10-18T05:36:03.563Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 98776 (99268)"
level=warn ts=2019-10-18T05:38:24.587Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 98793 (99484)"
level=warn ts=2019-10-18T05:53:47.599Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 100590 (100913)"
level=warn ts=2019-10-18T05:58:25.597Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 101041 (101372)"

**my alertmanager log:**
kubectl log -n monitoring alertmanager-main-2 alertmanager
log is DEPRECATED and will be removed in a future version. Use logs instead.
level=info ts=2019-10-18T05:54:01.032Z caller=main.go:197 msg="Starting Alertmanager" version="(version=0.18.0, branch=HEAD, revision=1ace0f76b7101cccc149d7298022df36039858ca)"
level=info ts=2019-10-18T05:54:01.032Z caller=main.go:198 build_context="(go=go1.12.6, user=root@868685ed3ed0, date=20190708-14:31:49)"
level=info ts=2019-10-18T05:54:01.330Z caller=cluster.go:623 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2019-10-18T05:54:01.466Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2019-10-18T05:54:01.466Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2019-10-18T05:54:01.471Z caller=main.go:429 msg=Listening address=:9093
level=info ts=2019-10-18T05:54:03.330Z caller=cluster.go:648 component=cluster msg="gossip not settled" polls=0 before=0 now=3 elapsed=2.000171583s
level=info ts=2019-10-18T05:54:09.331Z caller=cluster.go:648 component=cluster msg="gossip not settled" polls=3 before=3 now=2 elapsed=8.000795779s
level=info ts=2019-10-18T05:54:17.332Z caller=cluster.go:640 component=cluster msg="gossip settled; proceeding" elapsed=16.002048206s
level=warn ts=2019-10-18T05:54:26.362Z caller=cluster.go:438 component=cluster msg=refresh result=failure addr=10.244.2.45:9094
level=warn ts=2019-10-18T05:54:26.548Z caller=cluster.go:438 component=cluster msg=refresh result=failure addr=alertmanager-main-1.alertmanager-operated.monitoring.svc:9094
level=warn ts=2019-10-18T05:54:26.567Z caller=cluster.go:438 component=cluster msg=refresh result=failure addr=alertmanager-main-2.alertmanager-operated.monitoring.svc:9094
level=warn ts=2019-10-18T05:54:31.348Z caller=cluster.go:438 component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated.monitoring.svc:9094

**Comment by brancz** [comment]
The alertmanager config is a Kubernetes `Secret`, not a `ConfigMap`.

**Comment by xcjing** [comment]
@brancz thank you, use Secret it work.
