### ISSUE TITLE
Bump prometheus-adapter and Grafana versions (at least)

### ISSUE THREAD

**Issue by albertdb** [coreos/kube-prometheus#267]
**What is missing?**

External metrics support (prometheus-adapter)
Elasticsearch as a source for logs (Grafana).

**Why do we need it?**

To be able to make use of those features. The first one is a must for us.

**Environment**

* kube-prometheus version:

    `I3d5fc3e38d8d8fdc6699f113908dd04f6e026c3d`

**Anything else we need to know?**:

Thanks.

**Comment by brancz** [comment]
Feel free to bump :) 

You can also bump these things yourself when you use the jsonnet based kube-prometheus.
