### ISSUE TITLE
alertmanger e-mail and wechat template not work 

### ISSUE THREAD

**Issue by xcjing** [coreos/kube-prometheus#278]
**alertmanger e-mail template and wechat template not work **

**The default alertmanger alert mail content and wechat content is too complex, I want to use my customized e-mail template, I config it as below, but which not work for me**

**Environment**
  **docker images -a|grep prome**

quay.io/coreos/prometheus-config-reloader v0.33.0 2d95323c37d6 5 weeks ago 17.6MB
quay.io/coreos/prometheus-operator v0.33.0 b4f609ce281e 5 weeks ago 42.1MB
quay.io/prometheus/prometheus v2.11.0 b97ed892eb23 3 months ago 126MB
quay.io/prometheus/alertmanager v0.18.0 ce3c87f17369 3 months ago 51.9MB
quay.io/prometheus/node-exporter v0.18.1 e5a616e4b9cf 4 months ago 22.9MB
quay.io/coreos/k8s-prometheus-adapter-amd64 v0.4.1 9dcf4b7170ef 10 months ago 60.7MB

**kubectl -n monitoring describe deployment prometheus-operator**

Name: prometheus-operator
Namespace: monitoring
CreationTimestamp: Thu, 17 Oct 2019 09:32:09 +0000
Labels: app.kubernetes.io/component=controller
app.kubernetes.io/name=prometheus-operator
app.kubernetes.io/version=v0.33.0
Annotations: deployment.kubernetes.io/revision: 1
kubectl.kubernetes.io/last-applied-configuration:
{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kuberne...
Selector: app.kubernetes.io/component=controller,app.kubernetes.io/name=prometheus-operator
Replicas: 1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType: RollingUpdate
MinReadySeconds: 0
RollingUpdateStrategy: 25% max unavailable, 25% max surge
Pod Template:
Labels: app.kubernetes.io/component=controller
app.kubernetes.io/name=prometheus-operator
app.kubernetes.io/version=v0.33.0
Service Account: prometheus-operator
Containers:
prometheus-operator:
Image: quay.io/coreos/prometheus-operator:v0.33.0
Port: 8080/TCP
Host Port: 0/TCP
Args:
--kubelet-service=kube-system/kubelet
--logtostderr=true
--config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
--prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.33.0
Limits:
cpu: 200m
memory: 200Mi
Requests:
cpu: 100m
memory: 100Mi
Environment:
Mounts:
Volumes:
Conditions:
Type Status Reason

Available True MinimumReplicasAvailable
Progressing True NewReplicaSetAvailable
OldReplicaSets:
NewReplicaSet: prometheus-operator-55b978b89 (1/1 replicas created)
Events:

* Kubernetes version information:

    **`kubectl version`**
    1.15.3

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
**my alertmanager.yaml**
global:
  resolve_timeout: 5m
  smtp_smarthost: smtp.qq.com:465
  smtp_from: xxxx@qq.com
  smtp_auth_username: xxxx@qq.com
  smtp_auth_password: lhhbntarlhckcagb
  smtp_require_tls: false
  smtp_hello: qq.com

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: email-me


  routes:
  - receiver: 'wechat'
    match:
      severity: warning  

receivers:
- name: email-me
  email_configs:
  - to: xxxx@yeah.net
    html: '{{ template "mail.html" . }}'
- name: 'wechat'
  wechat_configs:
  - corp_id: "ww74f69a121f9eb681"
    api_secret: "XTMA3bmFjkr9PwkeXWK7-_C-3fiEcGgJoPxxsssssw"
    agent_id: "1000002"
    to_user: "@all"
    message: '{{ template "wechat.html" . }}'
    send_resolved: true

**my mail.tmpl:**
{{ define "mail.html" }}
<table border="1">
        <tr>
                <td>alert name</td>
                <td>instance</td>
                <td>value</td>
                <td>start time</td>
        </tr>
        {{ range $i, $alert := .Alerts }}
                <tr>
                        <td>{{ index $alert.Labels "alertname" }}</td>
                        <td>{{ index $alert.Labels "instance" }}</td>
                        <td>{{ index $alert.Annotations "value" }}</td>
                        <td>{{ $alert.StartsAt }}</td>
                </tr>
        {{ end }}
</table>
{{ end }}

**my wechat.tmpl:**
{{ define "wechat.html" }}
  {{ range $i, $alert := .Alerts.Firing }}
    [alert name]:{{ index $alert.Labels "alertname" }}
    [instance]:{{ index $alert.Labels "instance" }}
    [value]:{{ index $alert.Annotations "value" }}
    [start time]:{{ $alert.StartsAt }}
  {{ end }}
{{ end }}


* Prometheus Operator Logs:

**```alertmanger-main-0 log**
level=error ts=2019-10-23T03:06:01.437Z caller=notify.go:367 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"wechat\" due to unrecoverable error: templating error: template: :1:12: executing \"\" at <{{template \"wechat.html\" .}}>: template \"wechat.html\" not defined"

Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:
for mail template, I not found error in the alertmanger-main-0 log, but the e-mail content is empty which I received 
for wechat template, from the log above, it's seem alertmanger cannot fond the wechat.tmpl.
who can telll me how to make the mail and wechat template work. thanks!

**Comment by brancz** [comment]
This is unrelated to the Prometheus Operator, it's about usage of Prometheus/Alertmanager.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
