### ISSUE TITLE
unable to fetch pod metrics for pods in default namespace

### ISSUE THREAD

**Issue by middlestone** [coreos/kube-prometheus#280]
**What happened?**
unable to fetch pod metrics for pods in default namespace, but not kube-system and monitoring namespace.

kubectl top pods
W1023 19:05:00.186630   38990 top_pod.go:266] Metrics not available for pod default/nginx-untrusted2, age: 25h56m33.186616443s
error: Metrics not available for pod default/nginx-untrusted2, age: 25h56m33.186616443s

kubectl top pods -n kube-system
NAME                                       CPU(cores)   MEMORY(bytes)
calico-kube-controllers-6c494d8776-dc5lt   0m           170Mi
calico-node-mlv44                          28m          390Mi
coredns-5c98db65d4-8gmsf                   3m           154Mi
coredns-5c98db65d4-fz8bp                   2m           154Mi
etcd-kylin                                 27m          576Mi
kube-apiserver-kylin                       41m          656Mi
kube-controller-manager-kylin              10m          144Mi
kube-proxy-7dp65                           2m           327Mi
kube-scheduler-kylin                       1m           73Mi

kubectl top pods -n monitoring
NAME                                   CPU(cores)   MEMORY(bytes)
alertmanager-main-0                    1m           167Mi
grafana-67c5f864cc-hwvfd               6m           226Mi
kube-state-metrics-594f87fdf7-llj48    0m           243Mi
node-exporter-tnn6q                    9m           241Mi
prometheus-adapter-5677b794bd-kv98m    1m           111Mi
prometheus-k8s-0                       104m         756Mi
prometheus-operator-79df446bd8-6ldql   0m           134Mi

kubectl logs prometheus-adapter-5677b794bd-kv98m -n monitoring
....
E1023 11:03:00.740182       1 reststorage.go:144] unable to fetch pod metrics for pod default/nginx-untrusted2: no metrics known for pod

**Did you expect to see some different?**
yes, "kubectl top pods" should work.

**How to reproduce it (as minimally and precisely as possible)**:
run the command "kubectl top pods"

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
kubectl -n monitoring describe deployment prometheus-operator
Name:                   prometheus-operator
Namespace:              monitoring
CreationTimestamp:      Wed, 23 Oct 2019 12:39:03 +0800
Labels:                 app.kubernetes.io/component=controller
                        app.kubernetes.io/name=prometheus-operator
                        app.kubernetes.io/version=v0.33.0
Annotations:            deployment.kubernetes.io/revision: 1
                        kubectl.kubernetes.io/last-applied-configuration:
                          {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kuberne...
Selector:               app.kubernetes.io/component=controller,app.kubernetes.io/name=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/component=controller
                    app.kubernetes.io/name=prometheus-operator
                    app.kubernetes.io/version=v0.33.0
  Service Account:  prometheus-operator
  Containers:
   prometheus-operator:
    Image:      quay.io/coreos/prometheus-operator:v0.33.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/kubelet
      --logtostderr=true
      --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
      --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.33.0
    Limits:
      cpu:     200m
      memory:  500Mi
    Requests:
      cpu:        100m
      memory:     300Mi
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   prometheus-operator-79df446bd8 (1/1 replicas created)
Events:          <none>

* Kubernetes version information:

    `kubectl version`
    
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/arm64"}

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

    kubeadm init --pod-network-cidr 192.168.0.0/16 --kubernetes-version 1.15.3

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
Insert Prometheus Operator logs relevant to the issue here
```
kubectl logs prometheus-adapter-5677b794bd-kv98m -n monitoring
....
E1023 11:03:00.740182       1 reststorage.go:144] unable to fetch pod metrics for pod default/nginx-untrusted2: no metrics known for pod

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```
kubectl logs prometheus-k8s-0 prometheus -n monitoring
level=info ts=2019-10-23T04:39:25.238Z caller=main.go:329 msg="Starting Prometheus" version="(version=2.11.0, branch=heads/v2.11.0, revision=4ef66003d9855ed2b7a41e987b33828ec36db34d)"
level=info ts=2019-10-23T04:39:25.238Z caller=main.go:330 build_context="(go=go1.12.9, user=root@Kylin, date=20191019-05:33:55)"
level=info ts=2019-10-23T04:39:25.238Z caller=main.go:331 host_details="(Linux 4.4.131-20190810.kylin.server-generic #kylin SMP Fri Aug 16 09:38:05 CST 2019 aarch64 prometheus-k8s-0 (none))"
level=info ts=2019-10-23T04:39:25.238Z caller=main.go:332 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-10-23T04:39:25.239Z caller=main.go:333 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-10-23T04:39:25.241Z caller=main.go:652 msg="Starting TSDB ..."
level=info ts=2019-10-23T04:39:25.241Z caller=web.go:448 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-10-23T04:39:25.255Z caller=main.go:667 fs_type=EXT4_SUPER_MAGIC
level=info ts=2019-10-23T04:39:25.255Z caller=main.go:668 msg="TSDB started"
level=info ts=2019-10-23T04:39:25.255Z caller=main.go:738 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-10-23T04:39:25.266Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-10-23T04:39:25.268Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-10-23T04:39:25.269Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-10-23T04:39:25.271Z caller=kubernetes.go:192 component="discovery manager notify" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-10-23T04:39:25.447Z caller=main.go:766 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-10-23T04:39:25.447Z caller=main.go:621 msg="Server is ready to receive web requests."
level=info ts=2019-10-23T04:39:28.537Z caller=main.go:738 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-10-23T04:39:28.544Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-10-23T04:39:28.545Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-10-23T04:39:28.637Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-10-23T04:39:28.639Z caller=kubernetes.go:192 component="discovery manager notify" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-10-23T04:39:28.751Z caller=main.go:766 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-10-23T04:40:35.704Z caller=main.go:738 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-10-23T04:40:35.718Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-10-23T04:40:35.720Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-10-23T04:40:35.721Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-10-23T04:40:35.723Z caller=kubernetes.go:192 component="discovery manager notify" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-10-23T04:40:35.777Z caller=main.go:766 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=warn ts=2019-10-23T05:02:10.752Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 311127 (311483)"
level=warn ts=2019-10-23T05:03:43.750Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 311127 (311595)"
level=warn ts=2019-10-23T05:05:17.750Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 311127 (311709)"
level=warn ts=2019-10-23T05:22:19.761Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 312705 (312953)"
level=warn ts=2019-10-23T05:25:38.760Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 312816 (313194)"
level=warn ts=2019-10-23T05:27:11.760Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 312931 (313308)"
level=warn ts=2019-10-23T05:42:36.769Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 314415 (314432)"
level=warn ts=2019-10-23T05:44:16.772Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 314175 (314555)"
level=warn ts=2019-10-23T05:48:31.770Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 314530 (314866)"
level=warn ts=2019-10-23T05:59:25.777Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 315656 (315661)"
level=warn ts=2019-10-23T06:03:25.781Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 315775 (315952)"
level=warn ts=2019-10-23T06:11:53.779Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 316086 (316572)"
level=warn ts=2019-10-23T06:22:42.787Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 316881 (317359)"
level=warn ts=2019-10-23T06:25:22.859Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 317174 (317556)"
level=warn ts=2019-10-23T06:34:46.040Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 317792 (318239)"
level=warn ts=2019-10-23T06:42:55.867Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 318775 (318835)"
level=warn ts=2019-10-23T06:44:28.798Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 318582 (318949)"
level=warn ts=2019-10-23T07:00:08.050Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 319460 (320091)"
level=warn ts=2019-10-23T07:02:40.877Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 320056 (320276)"
level=warn ts=2019-10-23T07:05:29.809Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 320169 (320481)"
level=warn ts=2019-10-23T07:20:11.060Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 321311 (321553)"
level=warn ts=2019-10-23T07:24:21.816Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 321703 (321859)"
level=warn ts=2019-10-23T07:26:29.887Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 321499 (322014)"
level=info ts=2019-10-23T07:39:35.177Z caller=compact.go:495 component=tsdb msg="write block" mint=1571805573716 maxt=1571810400000 ulid=01DQVRWZMPNEQDHT0WNJ0A0Z6M duration=1.266267575s
level=info ts=2019-10-23T07:39:35.545Z caller=head.go:586 component=tsdb msg="head GC completed" duration=92.133501ms
level=warn ts=2019-10-23T07:42:52.070Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 322775 (323210)"
level=warn ts=2019-10-23T07:45:02.826Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 323080 (323369)"
level=warn ts=2019-10-23T07:46:34.896Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 323237 (323480)"
level=warn ts=2019-10-23T08:04:12.080Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 324430 (324765)"
level=warn ts=2019-10-23T08:08:42.041Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 324588 (325095)"
level=warn ts=2019-10-23T08:09:15.907Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 324702 (325135)"
level=warn ts=2019-10-23T08:25:00.090Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 325987 (326283)"
level=warn ts=2019-10-23T08:30:31.916Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 326355 (326688)"
level=warn ts=2019-10-23T08:31:59.052Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 326314 (326793)"
level=warn ts=2019-10-23T08:44:43.148Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 327505 (327723)"
level=warn ts=2019-10-23T08:48:58.924Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 327908 (328032)"
level=warn ts=2019-10-23T08:52:31.062Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 328016 (328292)"
level=info ts=2019-10-23T09:00:05.087Z caller=compact.go:495 component=tsdb msg="write block" mint=1571810400000 maxt=1571817600000 ulid=01DQVXGC8EM3ZDW2FFWEASNHHA duration=1.360507047s
level=info ts=2019-10-23T09:00:05.443Z caller=head.go:586 component=tsdb msg="head GC completed" duration=90.854634ms
level=warn ts=2019-10-23T09:06:23.158Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 328942 (329304)"
level=warn ts=2019-10-23T09:07:16.933Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 329256 (329367)"
level=warn ts=2019-10-23T09:12:14.072Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 329514 (329731)"
level=warn ts=2019-10-23T09:27:49.166Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 330524 (330868)"
level=warn ts=2019-10-23T09:31:28.081Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 330951 (331134)"
level=warn ts=2019-10-23T09:33:04.943Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 330589 (331251)"
level=warn ts=2019-10-23T09:52:06.954Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 332472 (332640)"
level=warn ts=2019-10-23T09:52:35.090Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 332354 (332674)"
level=warn ts=2019-10-23T09:52:56.175Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 332090 (332701)"
level=warn ts=2019-10-23T10:10:31.255Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 333921 (333983)"
level=warn ts=2019-10-23T10:11:46.964Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 333863 (334075)"
level=warn ts=2019-10-23T10:16:43.102Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 333897 (334449)"
level=warn ts=2019-10-23T10:27:43.262Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 335221 (335256)"
level=warn ts=2019-10-23T10:32:34.974Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 335315 (335610)"
level=warn ts=2019-10-23T10:40:19.112Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 335673 (336173)"
level=warn ts=2019-10-23T10:48:03.272Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 336480 (336746)"
level=warn ts=2019-10-23T10:51:54.143Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 336836 (337026)"
level=warn ts=2019-10-23T10:59:14.121Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 337401 (337562)"
level=info ts=2019-10-23T11:00:05.067Z caller=compact.go:495 component=tsdb msg="write block" mint=1571817600000 maxt=1571824800000 ulid=01DQW4C3GF9ZWE52YJJX1QMKDB duration=1.339741641s
level=info ts=2019-10-23T11:00:05.484Z caller=head.go:586 component=tsdb msg="head GC completed" duration=120.565935ms
level=info ts=2019-10-23T11:00:07.050Z caller=head.go:656 component=tsdb msg="WAL checkpoint complete" first=0 last=1 duration=1.565515989s
level=warn ts=2019-10-23T11:07:52.281Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 337966 (338190)"
level=warn ts=2019-10-23T11:09:32.153Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Endpoints ended with: too old resource version: 338247 (338313)"

**Anything else we need to know?**:

**Comment by middlestone** [comment]
the yaml file of the nginx-untrusted.yaml is just as below, do I miss anything in yaml file? if I create it in monitoring namespace or kube-system namespace, it is unbable to get the metrics too. 

cat nginx-untrusted.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-untrusted
  annotations:
    io.kubernetes.cri.untrusted-workload: "true"
spec:
  containers:
    - name: nginx
      image: nginx

**Comment by brancz** [comment]
If you query Prometheus directly, do you see metrics about this pod/container?

**Comment by middlestone** [comment]
thanks brancz for your reply, I think the problem is kata-containers. The runtime I use is not runc, if I run the container used runc, it is normal.

It seems that I need to learn more details, if you can provide any suggestions, I really appreciate.

**Comment by middlestone** [comment]
@brancz pods can be found via query prometheus directly.

![image](https://user-images.githubusercontent.com/8234516/67446265-a4858900-f642-11e9-8c8b-8dfc5406018e.png)

![image](https://user-images.githubusercontent.com/8234516/67446299-c5e67500-f642-11e9-969b-46d8af7e63c6.png)

**Comment by brancz** [comment]
Yes that probably doesn’t work with cAdvisor which is the component in kubernetes that exposes the container metrics. What you shared in the previous comment comes from kube state metrics which just looks at the kubernetes api, not real time measurements of the process.

You should open an issue on cadvisor to fix this.

**Comment by middlestone** [comment]
@brancz thank you very much for your help, considering metrics-server works fine, and metrics-server calls the api of kubelet which integrates the cadvisor to get the metrics, do you think cadavior may have problem? i am sorry that i am a new one to kubernetes, If i make any mistake, please give me a guide. thanks

BTW,  I don't know the difference between metrics-server and the resource metrics API server of kube-prometheus, and how to verify them.

**Comment by brancz** [comment]
metrics server doesn't work through cadvisor (yet) unfortunately, it works through the CRI stats endpoints which expose exactly the two metrics the metrics-server exposes via kubectl top. I wrote an experiment a long time ago [here](https://github.com/brancz/kube-pod-exporter), no guarantee it works, but that kind of approach could get you those metrics in prometheus format. That said pretty much none of the dashboards we have would work with those metrics unfortunately.

**Comment by brancz** [comment]
You've encountered one of the more sad parts of kubernetes instrumentation, as this is very much inconsistent for every container runtime and there is no clear plan really in place in Kubernetes to fix this. This is a pretty huge effort that so far no one has taken on.

**Comment by middlestone** [comment]
your information is really important to me，thank you! I will close this issue and struggle to find a workaround,:)
