### ISSUE TITLE
NodeFilesystemSpaceFillingUp is triggered before kubelet gc could start

### ISSUE THREAD

**Issue by mazzy89** [coreos/kube-prometheus#294]
**What happened?**

The alert `NodeFilesystemSpaceFillingUp` is triggered because the filesystem is used more than 81%.

In my case, filesystem space is occupied mostly by Docker images.

**Did you expect to see some different?**

I'd expect to see in action the kubelet GC but the default values are https://github.com/kubernetes/kubernetes/blob/e1fdaa177f60e280669aef94074a21efd0d928ea/pkg/kubelet/apis/config/v1beta1/defaults_linux.go

So this means that this alarm triggers in many clusters out there except for those who tune these settings.

Which is your opinion here? Would you tune kubelet GC to be more aggressive and kick in before the alarm would be triggered? So for example set `imagefs.available": "45%`

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

v0.33.0

* Kubernetes version information:

v1.14.6

* Kubernetes cluster kind:

kops

**Anything else we need to know?**:

**Comment by brancz** [comment]
Is the warning alert the one that fires for you or the critical one? These alerts come from the general node mixin, which nominally has nothing to do with kubernetes, so if anything then we need to make things configurable there to fit the kubernetes case.

**Comment by mazzy89** [comment]
It is the warning one. yep, that's true. these alerts rely on the node-exporter metrics and don't have any context about kubernetes operations.

What do you propose here @brancz?

**Comment by brancz** [comment]
The alert should probably be more configurable in the node mixin.

**Comment by mazzy89** [comment]
Yeah, make sense. Then I would open an issue and possibly a PR here https://github.com/prometheus/node_exporter/tree/master/docs/node-mixin.

**Comment by mazzy89** [comment]
Closing this. Thank you @brancz

**Comment by brancz** [comment]
I'd be ok with leaving this open here as we would probably want a specific setting in kube-prometheus for the node mixin.

**Comment by mazzy89** [comment]
Oh make sense. Reopning then.

**Comment by iuriaranda** [comment]
Any updates on this? We're experiencing the same behaviour and we're unsure on how to tackle it. Should we decrease the GC threshold to something like 79%, or should we fine-tune the alert so it only fires when the available disk space drops below 15%?

Also, @mazzy89 did you end up opening an issue on the node_exporter repo? If so, could you link it? I couldn't find it.

**Comment by mazzy89** [comment]
For the moment we are just living with the warnings that disappear after a while because the kubelet GC kicks in and clean the node.

This kind of alerts requires to be tuned according the kubelet GC, I believe that each cluster has different settings so I'm not sure how to make the configuration tunable and work for all the cases.

The issue anyway is not needed to be opened under node_exporter but under kube-prometheus.

**Comment by brancz** [comment]
As said above this first needs to be made configurable in our dependency that we use for node monitoring. Then we can fix it here.

**Comment by iuriaranda** [comment]
I'm willing to contribute on that regard, but I first wanted to validate the approach.

So you'd rather adjust the alert thresholds than adjust the kubelet GC settings, right? If so, the place to make these alerts configurable is the node_exporter repo, correct?

**Comment by brancz** [comment]
Correct! :)

**Comment by iuriaranda** [comment]
I've created a PR on the `node_exporter` project: https://github.com/prometheus/node_exporter/pull/1624

I think it should cover this use case, right?

**Comment by iuriaranda** [comment]
Ok, the PR in the node_exporter project is merged. Now, what would be the next steps on this repo?

Considering the kubelet triggers GC at 85% by default, I'd set the critical alert threshold at 85% or 86%. What do you think?

**Comment by brancz** [comment]
Sounds good!

**Comment by iuriaranda** [comment]
Here you go: https://github.com/coreos/kube-prometheus/pull/432

**Comment by paulfantom** [comment]
Closing as related PR is merged.

**Comment by christopheblin** [comment]
I have a brand new install of the helm chart (https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) and I'm seeing these alerts 

Labels
alertname = NodeFilesystemSpaceFillingUp
container = node-exporter
device = /dev/sda1
job = node-exporter
mountpoint = /
namespace = monitoring
pod = prometheus-operator-prometheus-node-exporter-pjh84
Annotations
description = Filesystem on /dev/sda1 at xxx has only 19.68% available space left and is filling up.

However, I dont understand why the threshold is 20% and not 15% (i.e if kubelet allows "imageGCHighThresholdPercent": 85, then it means 15% should be available)

Am I misunderstanding something here ?

Should I open another issue ?

**Comment by arajkumar** [comment]
@christopheblin There are 2 thresholds(for warning & critical alert) related to NodeFilesystemSpaceFillingUp. `fsSpaceFillingUpCriticalThreshold` was set to 15% to align with kubelet `imageGCHighThresholdPercent: 85` and `fsSpaceFillingUpWarningThreshold` was set to 20% to align with `imageGCLowThresholdPercent: 80`.

**Comment by christopheblin** [comment]
@arajkumar thanks for your answer !

Ok so I'm hitting the warning alert and not the critical ... and this is considered "normal"

As a newcomer to k8s monitoring and kube-prometheus, I'd argue that it is kind of "weird/strange" that I'm required to silence an alert from the monitoring stack day 1 :)

unless there is something I can do somewhere and that I've missed :)

**Comment by arajkumar** [comment]
>Ok so I'm hitting the warning alert and not the critical ... and this is considered "normal"

@hristopheblin, I'm not saying this is "normal" :), as the default kubelet GC suppose to happen on every 2m. Probably there might be other contributors?

**Comment by christopheblin** [comment]
@arajkumar thank you for your precisions and sorry if I misunderstood you

I should not have the warning because the GC should happen every 2m and so hitting lowThresholdPercent should NOT happen -> is that what you meant ?

if yes, I still do not see what is causing this issue on the pod prometheus-operator-prometheus-node-exporter-pjh84 directly created from the kube-primetheus helm chart ...

When I search for "NodeFilesystemSpaceFillingUp node-exporter", this issue is among the top answers and the single one that is providing some pointers

Would you have any other clue / pointers on why this is happening ? is there something I can look at ?

**Comment by christopheblin** [comment]
@arajkumar thanks again for the answer !

the thing is that this pod is directly created by https://github.com/prometheus-community/helm-charts, I do not even know what there is exactly inside this pod ...

unfortunately, I cannot find time to diagnose more in depth so, at the moment, I ignored the alert in the alertmanager when severity=warning :(

I'll try to open another issue once I will be able to investigate 

thanks again for the support, at least I am now confident that this will not blow up inadvertently :)

**Comment by arajkumar** [comment]
>the thing is that this pod is directly created by https://github.com/prometheus-community/helm-charts, I do not even know what there is exactly inside this pod ...

You don't need to worry about the things inside the pod, In this case [node_exporter pod mounts](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/templates/daemonset.yaml#L157) the host/node file-system to expose metrics related to fs mounts. 

So the quick thing to do is to get into the node where the node_exporter pod runs(it will run all k8s nodes, as it a daemonset) and see how much space the root fs still has(du ..).
