### ISSUE TITLE
/metrics: context deadline exceeded

### ISSUE THREAD

**Issue by anstns** [coreos/kube-prometheus#306]
![1](https://user-images.githubusercontent.com/36152763/68917735-8c6ada80-07a6-11ea-890c-6bdc21dd4185.png)
![屏幕快照 2019-11-15 下午12 51 22](https://user-images.githubusercontent.com/36152763/68917758-a4daf500-07a6-11ea-8074-9f7f480335ed.png)
![屏幕快照 2019-11-15 下午12 52 32](https://user-images.githubusercontent.com/36152763/68917811-cdfb8580-07a6-11ea-9d96-af25862c48e4.png)
![屏幕快照 2019-11-15 下午12 53 23](https://user-images.githubusercontent.com/36152763/68917843-ecfa1780-07a6-11ea-87c4-300de240843a.png)
Can only monitor the primary node

**Comment by brancz** [comment]
Things like this are almost always a firewall issue. Can you make sure that you can wget or curl the endpoint from the Prometheus pod?
