### ISSUE TITLE
Mark grafana, prometheus and alert manager as cluster-service

### ISSUE THREAD

**Issue by gianrubio** [coreos/kube-prometheus#31]
What do you think to mark grafana, prometheus and alert manager as a kubernetes.io/cluster-service?

http://kubernetes.io/docs/admin/cluster-components/
http://kubernetes.io/docs/user-guide/kubectl/kubectl_cluster-info/

**Comment by brancz** [comment]
I have no objections. Feel free to open a PR 🙂
