### ISSUE TITLE
should we add  podAntiAffinity for prometheus and alertmanager ?

### ISSUE THREAD

**Issue by zgfh** [coreos/kube-prometheus#316]
**What is missing?**
if all pod of alertmanager on one node ,it is dangerous, should we add podAntiAffinity to split up them ?

**Comment by brancz** [comment]
I was under the impression that we already do :scream: . Please go ahead and add it! :slightly_smiling_face:

**Comment by praseodym** [comment]
The [anti-affinity mixin](https://github.com/coreos/kube-prometheus#pod-anti-affinity) should take care of that?

**Comment by brancz** [comment]
Ah right! :) Does that solve it for you @zgfh ?

**Comment by zgfh** [comment]
@praseodym @brancz thanks a lot, it should work .
