### ISSUE TITLE
prometheus-adapter cannot collect container-level cpu/memory metrics

### ISSUE THREAD

**Issue by jrockway** [coreos/kube-prometheus#319]
**What happened?**

I have seen a bunch of bugs along the lines of "`kubectl top pods` stopped working".  I think I have figured out what's going on.

On my stock `k3s version v1.0.0 (18bd921c)` cluster with a relatively-default configuration of kube-prometheus[1], out of the box, `kubectl top pods` indeed doesn't work.  The problem is that the included prometheus-adapter configuration specifies a query like:

`sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>,container!="POD",container!="",pod!=""}[5m])) by (<<.GroupBy>>)`

This yields an error because no metrics in Prometheus match the selector `container!=""`, it's empty for every metric.  If you change the rule to:

`sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>,pod!=""}[5m])) by (<<.GroupBy>>)`

Then everything works fine.  Except for `kubectl top pods --containers`; Prometheus does not have the container-level data, so it can't provide that information.  (And that probably breaks things like the Vertical Pod Autoscaler, not that I've used it.)

An instance of `metrics-server` in the same cluster, however, DOES provide container-level metrics.  The question is why.

Looking at the raw metrics endpoint on the kubelet, we can `grep -v 'container=""'` and note that no lines match.  Indeed, the /metrics/cadvisor endpoint seems to not contain any container-related information.  Each line looks something like:

`container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods/besteffort/pod6a8ecf61-cd94-4919-b1e1-0f4d3b7c0862",image="",name="",namespace="observability",pod="jaeger-78696dcf78-6vv8b"} 2.304237937 1575665390322`

So how does `metrics-server` get the container-level data?  It looks like it is hitting a completely different endpoint on the kubelet, `/stats/summary?only_cpu_and_memory=true`.  This returns some JSON that does have per-container information:

```
  ...
   "containers": [
    {
     "name": "jaeger",
     "startTime": "2019-12-06T19:42:38Z",
     "cpu": {
      "time": "2019-12-06T21:08:59Z",
      "usageNanoCores": 448133,
      "usageCoreNanoSeconds": 2873034112
     },
     "memory": {
      "time": "2019-12-06T21:08:59Z",
      "workingSetBytes": 6950912
     }
    }
   ...
  },
```

Anyway, I am not sure what action should be taken here.  Maybe it's a bug with k3s (but my DigitalOcean managed cluster behaves in exactly the same way), or maybe it's a symptom of using plain containerd instead of docker.  But under whatever circumstances we're encountering here, the default install of `kube-prometheus` is very happy to overwrite a completely-working `metrics-server` and break anything that uses metrics.  I am not satisfied with the workaround of removing the match on the container!="" because now there is less data for autoscalers and `kubectl top` to use.  I think `prometheus-adapter` should just be made into an optional component, so as not to break working metrics setups.  (If people want to autoscale based on prometheus metrics, then they can manually install it.)

This might also be a kubelet bug, or a k3s bug, or a digitalocean bug.  I keep seeing chatter about removing cadvisor from the kubelet completely, so it's not clear to me that this method of getting cpu/mem usage into prometheus will continue to work in the future.  Not sure.  Just wanted to report my findings so that others wondering about this have more information.

**Environment**

* Prometheus Operator version:

`quay.io/coreos/prometheus-operator:v0.34.0`

Full config: https://github.com/jrockway/jrock.us/blob/f9c3960d80d5d234a398609a11ff3c0a81b4cb92/production/prometheus/config.jsonnet (link [1] from above)

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-18T14:56:51Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3-k3s.2", GitCommit:"e7e6a3c4e9a7d80b87793612730d10a863a25980", GitTreeState:"clean", BuildDate:"2019-11-18T18:31:23Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

k3s

* Manifests:

See above github link.

* Prometheus Operator Logs:

N/A

* Prometheus Logs:

N/A

**Comment by brancz** [comment]
The prometheus-adapter is part of the default kube-prometheus stack. You're of course free to remove it if you prefer to run metrics-server. I hope you understand that we won't always be able to satisfy everyone's needs with the default configuration, but we try to provide the most complete one.

That said, this seems like the k3s kubelet/cadvisor are exposing metrics incorrectly here. I believe the summary API uses the CRI stats endpoints served by cri-containerd directly instead of cadvisor, which would explain why the summary API works as expected. I would create a bug against k3s.

**Comment by annismckenzie** [comment]
Yes, it's a bug in k3s and you can fix the missing metrics using https://github.com/rancher/k3s/issues/473#issuecomment-575919050.

**Comment by brancz** [comment]
In that case closing here. Thanks @annismckenzie !
