### ISSUE TITLE
Allow to specify node_exporter version

### ISSUE THREAD

**Issue by omerlh** [coreos/kube-prometheus#344]
**What is missing?**
The ability to change node_exporter version

**Why do we need it?**
Allow users to use the version they want, I tried the following which didn't worked:
```jsonnet
    nodeExporter+:: {
      _config+:: {
        versions+:: {
          nodeExporter: 'v0.18.1',
          kubeRbacProxy: 'v0.4.1',
        },
      },
      local daemonset = k.apps.v1.daemonSet,

      daemonset+:
        daemonset.mixin.spec.template.spec.withNodeSelector({ 'beta.kubernetes.io/os': 'linux' }),
    },
```
I know I can write the entire spec again and do what I want, but it requires me to duplicate a lot of code just for changing a version :)

**Environment**
Kubernetes

* kube-prometheus version:

    `Insert Git SHA here`

**Anything else we need to know?**:

**Comment by brancz** [comment]
`_config` should be at the top level instead of nested in `nodeExporter`.

**Comment by omerlh** [comment]
Thanks, I missed that somehow :)
