### ISSUE TITLE
Should we change Scheduler and ControllerManager ServiceMonitors to PodMonitors?

### ISSUE THREAD

**Issue by Aracki** [coreos/kube-prometheus#349]
That way we would not need Services that expose `kube-controller-manager` & `kube-scheduler` metrics ports.

If that seems like a good idea, I can make a PR.

**Comment by yeya24** [comment]
Duplicate with https://github.com/coreos/kube-prometheus/issues/169

**Comment by Aracki** [comment]
Yeah definitely a duplicate. Thanks @yeya24

**Comment by brancz** [comment]
Still open to be tackled as far as I know :)
