### ISSUE TITLE
What is the reason behind shrinking the node.rules

### ISSUE THREAD

**Issue by Aracki** [coreos/kube-prometheus#352]
I have notices in manifests we are missing a lot of old "node:" records from `node.rules`. They have been removed in last 6 months, but I cannot find the reason behind the removal. 

e.g.
```
    - expr: |
        sum by (node) (
          (irate(node_network_receive_bytes_total{job="node-exporter",device!~"veth.+"}[1m]) +
          irate(node_network_transmit_bytes_total{job="node-exporter",device!~"veth.+"}[1m]))
        * on (namespace, pod) group_left(node)
          node_namespace_pod:kube_pod_info:
        )
      record: node:node_net_utilisation:sum_irate
```

**Comment by Aracki** [comment]
After a quite research, I have found out they can be found within [node-mixin in node_exporter repo](https://github.com/prometheus/node_exporter/tree/master/docs/node-mixin).

Is that the reason why `kube-prometheus` will not maintain node alerts and rules in future?

**Comment by brancz** [comment]
> Is that the reason why kube-prometheus will not maintain node alerts and rules in future?

That's correct. Essentially we're decentralizing most of the configurations in to the projects they belong to themselves, making kube-prometheus more of a meta-project.

**Comment by Aracki** [comment]
@brancz That makes sense. Thanks for the answer!
