### ISSUE TITLE
unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec

### ISSUE THREAD

**Issue by Omenien** [coreos/kube-prometheus#353]
**What happened?**
As of #332, the prometheus-operator CustomResourceDefinitions have been updated to set `$.spec.preserveUnknownFields`. This field is not available in Kubernetes versions < 1.15.0 resulting in the error 
```
error validating data: ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec
```

**Did you expect to see some different?**
The root README.md explicitly mentions that Kubernetes versions < 1.14.0 must use the `release-0.1` branch instead of `master` but there is no such provision for Kubernetes versions < 1.15.0. 

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to use kube-prometheus master with a Kubernetes cluster with a version less than 1.15.0.

**Environment**

* Prometheus Operator version:

    `9493a1a5f7090dca406a0e80d1986484c70c1acf`

* Kubernetes version information:

    `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: EKS

* Manifests:

```
manifests/setup/prometheus-operator-0alertmanagerCustomResourceDefinition.yaml 
manifests/setup/prometheus-operator-0podmonitorCustomResourceDefinition.yaml 
manifests/setup/prometheus-operator-0prometheusCustomResourceDefinition.yaml 
manifests/setup/prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
manifests/setup/prometheus-operator-0servicemonitorCustomResourceDefinition.yaml 
```

* Prometheus Operator Logs: N/A

* Prometheus Logs: N/A

**Anything else we need to know?**: N/A

**Comment by christiangda** [comment]
I've got the same error.  Until now I'm using the release-0.3 branch to avoid the error

**Comment by wy100101** [comment]
Just an FYI, I'm seeing this problem with GKE version 1.16.6-gke.18

Interestingly, the server version is still 1.14+. No idea what that is about:
 ```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

```
