### ISSUE TITLE
Use kube-state-metrics jsonnet dependency 

### ISSUE THREAD

**Issue by lilic** [coreos/kube-prometheus#369]
As kube-state-metrics now has switched to including [jsonnet](https://github.com/kubernetes/kube-state-metrics/tree/master/jsonnet) we should remove ours in favour of that and bring it in as a dependency. Same goes for the alerts.

See https://github.com/coreos/kube-prometheus/pull/368#issuecomment-572694051

**Comment by olegmayko** [comment]
I can submit PR after holidays (beginning of Feb). would it be okay?

**Comment by brancz** [comment]
If no one will have done it by then, please! :)

**Comment by LiliC** [comment]
Yes go for it! Thanks!

**Comment by olegmayko** [comment]
Hi, I had a quick look into the ksm lib on kube-prometheus, it contains additionally ksm autoscaler. Thus, there are 2 possibilities: 
* remove autoscaler and generate sts (which has autosharding) which can replace ksm autoscaler in some way; 
* keep autoscaler and just use standard deployment from kube-state-metrics repo. 
what do you think?
//cc @brancz 
//cc @LiliC

**Comment by brancz** [comment]
I think we should default to the standard deployment. We can figure out afterwards how people might be able to opt into the autosharding feature with the statefulset.

**Comment by LiliC** [comment]
I would like to end up with the similar deployment we already have in this repo just that it uses the upstream jsonnet. In a follow up issue we should look at how to easily opt into the new autosharding feature. Main point of this issue is to remove the ned to manually update the ksm deployments.

**Comment by lilic** [comment]
I think this can be closed now. If we need to do follow up we can open a new issue.
