### ISSUE TITLE
resource limits customization

### ISSUE THREAD

**Issue by a8j8i8t8** [coreos/kube-prometheus#372]
**What happened?**
Alertmanager and prometheus-k8s are failing to start with error `minimum memory usage per Container is 90Mi, but request is 25Mi`

Is there a way to customize this? Any workaround?
**Environment**

I installed everything from master branch on Kubernetes cluster `1.15.7`.

_Cheers,_
_- Ajit_

**Comment by brancz** [comment]
You can set the memory requested by the sidecar containers via the “--config-reloader-memory“ flag.

**Comment by a8j8i8t8** [comment]
Thanks for your reply @brancz .
I assume this argument is for `prometheus-operator` deployment. Is my assumption correct?

_Cheers,_
_-Ajit_

**Comment by brancz** [comment]
Correct

**Comment by a8j8i8t8** [comment]
Thanks. Closing this.
