### ISSUE TITLE
KubeCPUOvercommit and KubeMemOvercommit considering non-scheduled pods

### ISSUE THREAD

**Issue by michelesr** [coreos/kube-prometheus#373]
**What happened?**

Alerts for `KubeCPUOvercommit` and `KubeMemOvercommit` are raising wrongly due to the fact that the rules are considering all the pods resource allocation, including pods that aren't scheduled (for example pods in `Completed` phase).

**Did you expect to see some different?**

Only scheduled pods should be considered requesting resources.

**How to reproduce it (as minimally and precisely as possible)**:

Run a kubernetes job, wait for the pod to get in the completed state, and verify that is still considered in the sum of pod allocated resources in the cluster.

**Environment**

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.34.0`
    

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    Amazon EKS

**Comment by brancz** [comment]
Which commit/version of kube-prometheus are you using?

https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/alerts/resource_alerts.libsonnet#L24-L41

Uses the recording rules `namespace:kube_pod_container_resource_requests_cpu_cores:sum` and `namespace:kube_pod_container_resource_requests_memory_bytes:sum` which only select on running and pending pods.

https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/c9607e32d8ed8f516750f5ccb6567ef391ef809a/rules/apps.libsonnet#L63-L90

**Comment by michelesr** [comment]
I see... does that work differently from `kube_pod_container_resource_requests_cpu_cores` and `kube_pod_container_resource_requests_memory_bytes`? I can see the completed pods appearing in those two metrics.

**Comment by brancz** [comment]
Yes those recording rules only include pods that are either in `Running` or `Pending` state.

**Comment by michelesr** [comment]
@brancz thanks: I've been too precipitous and haven't investigated enough, it looks like the rules are behaving properly, so I'm gonna close the issue.
