### ISSUE TITLE
Deprecated metrics mixin drops too many time series

### ISSUE THREAD

**Issue by bgagnon** [coreos/kube-prometheus#377]
In k8s 1.14, the following metrics were deprecated:
* `kubelet_runtime_operations`
* `kubelet_runtime_operations_latency_microseconds`
* `kubelet_runtime_operations_errors`

They were renamed to fit naming conventions:
* `kubelet_runtime_operations_total`
* `kubelet_runtime_operations_duration_seconds`
* `kubelet_runtime_operations_errors_total`

However, the mixin that drops deprecated time series (`dropping-deprecated-metrics-relabelings.libsonnet`) is a little too aggressive:

```jsonnet
  // Drop all kubelet metrics which are deprecated in kubernetes.
  {
    sourceLabels: ['__name__'],
    regex: 'kubelet_(pod_worker_latency_microseconds|pod_start_latency_microseconds|cgroup_manager_latency_microseconds|pod_worker_start_latency_microseconds|pleg_relist_latency_microseconds|pleg_relist_interval_microseconds|runtime_operations|runtime_operations_latency_microseconds|runtime_operations_errors|eviction_stats_age_microseconds|device_plugin_registration_count|device_plugin_alloc_latency_microseconds|network_plugin_operations_latency_microseconds).*',
    action: 'drop',
  },
```

The trailing `.*` in the regex is causing the new time series to be dropped along with the old ones.

This breaks the _Kubernetes / Kubelet_ dashboard -- every graph reports _No data_.

**Comment by LiliC** [comment]
Thanks for reporting the issue, will work on the fix!
