### ISSUE TITLE
[Feature Requests] Monitoring attached disks

### ISSUE THREAD

**Issue by andrewhowdencom** [coreos/kube-prometheus#38]
I haven't' see where this possible yet, but I feel like it should be. If you've done it, awesome (: If you haven't, it'd be a cool challenge!

**Comment by gianrubio** [comment]
@andrewhowdencom see https://github.com/prometheus/node_exporter/issues/332#issuecomment-265680303

**Comment by andrewhowdencom** [comment]
<3 I'll have a look later today!

**Comment by brancz** [comment]
Can this be closed @andrewhowdencom ?

**Comment by andrewhowdencom** [comment]
Please do. (:
