### ISSUE TITLE
Failed to fetch https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/index.yaml : 403 Forbidden

### ISSUE THREAD

**Issue by marcindulak** [coreos/kube-prometheus#385]
I'm looking for an old version of kube-prometheus helm chart, but it seems like the old coreos-charts repo is no longer accessible. I've asked the same question on #prometheus-operator slack.

**What did you do?**

```sh
helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
```

```sh
helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable
Error: Looks like "https://s3-eu-west-1.amazonaws.com/coreos-charts/stable" is not a valid chart repository or cannot be reached: Failed to fetch https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/index.yaml : 403 Forbidden
```

**Did you expect to see some different?**

**Environment**

* Kubernetes version information:

   ```
   kubectl version
   Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:14:38Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
   Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-12-04T08:00:52Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
   ```

**Anything else we need to know?**:

The preferable solution is to bring the repository back, or transfer it to another url. Then provide a deprecation notice so a mirror can be made or at least the charts stored locally.

See also https://github.com/NVIDIA/deepops/issues/410

**Comment by brancz** [comment]
This happened over a year ago and the deprecation message is here https://github.com/coreos/prometheus-operator/blob/master/helm/README.md

Closing here, but let us know if you have any more questions.

**Comment by marcindulak** [comment]
It seems like not all charts were transferred from `https://s3-eu-west-1.amazonaws.com/coreos-charts/stable`. I'm looking specifically for 0.0.21 chart version of kube-prometheus, and 0.0.11 version of prometheus-operator.

Is there any way to fetch them from elsewhere than the coreos-charts/stable repo? The workaround repo `https://nvidia.github.io/gpu-monitoring-tools/helm-charts` used by nvidia does not contain these specific versions either.

**Comment by brancz** [comment]
All the charts were migrated to the upstream charts repo as none of the prometheus operator maintainers use or maintain them.

@vsliouniaev do you maybe have some hints for @marcindulak ?

**Comment by vsliouniaev** [comment]
The old charts were not transferred in any way, but a new chart has replaced them. The old chart sources are still in the coreos/prometheus-operator repository history. Here is the commit for the chart versions you're looking for: https://github.com/coreos/prometheus-operator/tree/bd95b847cd57aaeb572e43ace81bc69b8411515e/helm
