### ISSUE TITLE
Grafana 4.1.1

### ISSUE THREAD

**Issue by tsloughter** [coreos/kube-prometheus#39]
Is there a reason the version of grafana used is 3.1.1 still? I'm going to try with 4.1.1, as it appears to be needed for some dashboards I'm trying to use, but wanted to check if there are known issues with upgrading from 3.1.1.

**Comment by brancz** [comment]
We have not attempted an update so far, simply because we didn't have the need for any new features, so if the upgrade is successful we're happy to merge it.

**Comment by urzds** [comment]
I think this can be closed? #40 was already merged.
