### ISSUE TITLE
I can not get scrape 0/0 up

### ISSUE THREAD

**Issue by jrcjoro** [coreos/kube-prometheus#399]
I tried to follow this example: https://developer-docs.citrix.com/projects/citrix-k8s-ingress-controller/en/latest/metrics/promotheus-grafana/ 

I tried with exact configs as in above site, but it didn't work, so I tried to change Labels to different versions as it was mentioned to be probable reason for not scraping but nothing worked.

Exporter Pod is running normally: $ curl http://10.20.0.4:8888
# HELP citrixadc_tcp_tot_rx_packets_total tcptotrxpkts
# TYPE citrixadc_tcp_tot_rx_packets_total counter
citrixadc_tcp_tot_rx_packets_total{nsip="10.32.122.1:80"} 1.52237059e+08

kube-prometheus version 0.34

$ kubectl -n monitoring get secret prometheus-k8s -ojson | jq -r '.data["prometheus.yaml.gz"]' | base64 -d | gunzip | grep "citrix-adc"
- job_name: default/citrix-adc-servicemonitor/0

jsonnet:
    serviceMonitorCitrixADC: {
        apiVersion: 'monitoring.coreos.com/v1',
        kind: 'ServiceMonitor',
        metadata: {
          name: 'citrix-adc-servicemonitor',
          namespace: 'default',
          labels: {
            'servicemonitor': 'citrix-adc',
          }, // labels
        }, // metadata
        spec: {
          endpoints: [
            {
              interval: '30s',
              port: 'exporter-port',
            },
          ],
          selector: {
            matchLabels: {
              app: 'exporter-vpx-ingress', 
            },
          }, // selector
          targetLabels: [ 
            'app',
          ],
          namespaceSelector: {
            matchNames: ['monitoring', 'default'],
          }, // namespace selector
        }, // spec   
    }, // servicemonitor

Prome config:
- job_name: default/citrix-adc-servicemonitor/0
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - monitoring
      - default
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_app]
    separator: ;
    regex: exporter-vpx-ingress
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: exporter-port
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Node;(.*)
    target_label: node
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Pod;(.*)
    target_label: pod
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_label_app]
    separator: ;
    regex: (.+)
    target_label: app
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: exporter-port
    action: replace

Exporter Pod
apiVersion: v1
kind: Pod 
metadata:
  name: exporter-vpx-ingress
  labels:
    app: exporter-vpx-ingress
spec:
  containers:
    - name: exporter
      image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.0
      imagePullPolicy: IfNotPresent
      args:
        - "--target-nsip=10.32.122.1:80"
        - "--port=8888"
---
kind: Service
apiVersion: v1
metadata:
  name: exporter-vpx-ingress
  labels:
    service-type: citrix-adc-monitor
spec:
  selector:
    name: exporter-vpx-ingress
  ports:
    - name: exporter-port
      port: 8888
      targetPort: 8888

I have no idea what I'm doing wrong here?

**Comment by jrcjoro** [comment]
up{job="default/citrix-adc-servicemonitor/0"} 
Load time: 34ms
Resolution: 14s
Total time series: 0

**Comment by brancz** [comment]
I don’t know that product, could you first contact the developers of that product to troubleshoot this with you and then follow up here with details of what might be wrong with the prometheus operator.

**Comment by jrcjoro** [comment]
Problem is not in that product, it's working as expected and exporter is offering metrics on port 8888 as expected. Problem is that I can not configure Prometheus to scrape those metrics?

**Comment by jrcjoro** [comment]
I can get all metrics from command line as expected: $ curl http://10.20.0.4:8888/metrics

**Comment by brancz** [comment]
But it provided you with a configuration that doesn’t work :)

**Comment by jrcjoro** [comment]
Metrics are there so there should be a way to configure jsonnet in a way that they get scraped, right?

**Comment by brancz** [comment]
Which namespace is the target running in? The way it’s currently configured it must be in default or monitoring namespace.

**Comment by jrcjoro** [comment]
It is in default namespace.

**Comment by jrcjoro** [comment]
$ kubectl describe servicemonitor citrix-adc-servicemonitor
Name:         citrix-adc-servicemonitor
Namespace:    default
Labels:       servicemonitor=citrix-adc
Annotations:  <none>
API Version:  monitoring.coreos.com/v1
Kind:         ServiceMonitor
Metadata:
  Creation Timestamp:  2020-01-30T12:35:38Z
  Generation:          1
  Resource Version:    4707143
  Self Link:           /apis/monitoring.coreos.com/v1/namespaces/default/servicemonitors/citrix-adc-servicemonitor
  UID:                 8fd42e8e-f6f9-4005-b646-bca89e6b499f
Spec:
  Endpoints:
    Interval:  30s
    Port:      exporter-port
  Namespace Selector:
    Match Names:
      monitoring
      default
  Selector:
    Match Labels:
      App:  exporter-vpx-ingress
Events:     <none>

**Comment by jrcjoro** [comment]
Is Prometheus trying to connect to ClusterIP:Port?

**Comment by jrcjoro** [comment]
It seems that ClusterIP is not connecting to exporter Pod.

**Comment by jrcjoro** [comment]
I was able to fix this problem by fixing exporter service, no I can scrape.
