### ISSUE TITLE
kubectl top pods command is not working (top nodes working fine).

### ISSUE THREAD

**Issue by gjkim42** [coreos/kube-prometheus#409]
Hi,

I applied kube-prometheus on my cluster, and basically it worked fine.
'kubectl top pods' command was also working fine.

However,
after deploying custom-metrics-api ( kube-prometheus/experimental/custom-metrics-api/deploy.sh ), 
prometheus-custom-metric itself is working
( I confirmed it with kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1) 
but, kubectl top pods is not working for all namespaces.

Here is my log,

    kubectl version
    Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
---
    kubectl get apiservice
    NAME                                   SERVICE                         AVAILABLE   AGE
    ...
    v1beta1.authorization.k8s.io           Local                           True        44m
    v1beta1.batch                          Local                           True        44m
    v1beta1.certificates.k8s.io            Local                           True        44m
    v1beta1.coordination.k8s.io            Local                           True        44m
    v1beta1.custom.metrics.k8s.io          monitoring/prometheus-adapter   True        34m
    v1beta1.discovery.k8s.io               Local                           True        44m
    v1beta1.events.k8s.io                  Local                           True        44m
    v1beta1.extensions                     Local                           True        44m
    v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   True        38m
    ...

---
    kubectl top nodes
    NAME     CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
    master   394m         9%     3152Mi          40%
    node0    304m         7%     2780Mi          35%

--- 
    kubectl top pod -nmonitoring
    W0210 15:32:35.174595   27242 top_pod.go:266] Metrics not available for pod kube-system/calico-kube-controllers-6b9d4c8765-gm8z4, age: 50m27.1745715s
    error: Metrics not available for pod kube-system/calico-kube-controllers-6b9d4c8765-gm8z4, age: 50m27.1745715s

---

    kubectl logs prometheus-adapter-5cd5798d96-xhc4s -nmonitoring
    I0210 05:52:11.596500       1 adapter.go:93] successfully using in-cluster auth
    I0210 05:52:12.312621       1 serving.go:273] Generated self-signed cert (/var/run/serving-cert/apiserver.crt, /var/run/serving-cert/apiserver.key)
    I0210 05:52:12.739745       1 serve.go:96] Serving securely on [::]:6443
    E0210 05:52:22.433890       1 writers.go:149] apiserver was unable to write a JSON response: http2: stream closed
    E0210 05:52:22.434031       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
    E0210 05:52:22.434126       1 writers.go:149] apiserver was unable to write a JSON response: http2: stream closed
    E0210 05:52:22.437022       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
    E0210 05:52:22.444996       1 writers.go:149] apiserver was unable to write a JSON response: http2: stream closed
    E0210 05:52:22.445014       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
    E0210 05:52:22.445163       1 writers.go:149] apiserver was unable to write a JSON response: http2: stream closed
    E0210 05:52:22.447166       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
    E0210 05:52:22.453647       1 writers.go:149] apiserver was unable to write a JSON response: http2: stream closed
    E0210 05:52:22.453668       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
    E0210 05:52:47.203302       1 provider.go:186] unable to fetch CPU metrics for pod monitoring/node-exporter-42g2l, skipping
    E0210 05:52:47.203339       1 provider.go:186] unable to fetch CPU metrics for pod kube-system/kube-scheduler-master, skipping
    E0210 05:52:47.203357       1 provider.go:186] unable to fetch CPU metrics for pod monitoring/alertmanager-main-2, skipping
    E0210 05:52:47.203374       1 provider.go:186] unable to fetch CPU metrics for pod monitoring/prometheus-adapter-5cd5798d96-xhc4s, skipping
    E0210 05:52:47.203390       1 provider.go:186] unable to fetch CPU metrics for pod kube-system/coredns-6955765f44-wjthv, skipping
    E0210 05:52:47.203406       1 provider.go:186] unable to fetch CPU metrics for pod kube-system/kube-proxy-p24hb, skipping
    E0210 05:52:47.203422       1 provider.go:186] unable to fetch CPU metrics for pod monitoring/grafana-58dc7468d7-skn9x, skipping
    E0210 05:52:47.203437       1 provider.go:186] unable to fetch CPU metrics for pod kube-system/calico-node-nqrn7, skipping
    E0210 05:52:47.203453       1 provider.go:186] unable to fetch CPU metrics for pod monitoring/alertmanager-main-0, skipping
    E0210 05:52:47.203468       1 provider.go:186] unable to fetch CPU metrics for pod kube-system/kube-apiserver-master, skipping
    E0210 05:52:47.203484       1 provider.go:186] unable to fetch CPU metrics for pod kube-system/coredns-6955765f44-k7cvl, skipping
    E0210 05:52:47.203499       1 provider.go:186] unable to fetch CPU metrics for pod monitoring/node-exporter-bx7d2, skipping
    ...
---
    kubectl get --raw /apis/metrics.k8s.io/v1beta1/nodes | jq . 
    {
      "kind": "NodeMetricsList",
      "apiVersion": "metrics.k8s.io/v1beta1",
      "metadata": {
        "selfLink": "/apis/metrics.k8s.io/v1beta1/nodes"
      },
      "items": [
        {
          "metadata": {
            "name": "master",
            "selfLink": "/apis/metrics.k8s.io/v1beta1/nodes/master",
            "creationTimestamp": "2020-02-10T06:38:08Z"
          },
          "timestamp": "2020-02-10T06:38:08Z",
          "window": "1m0s",
          "usage": {
            "cpu": "382m",
            "memory": "3233124Ki"
          }
        },
        {
          "metadata": {
            "name": "node0",
            "selfLink": "/apis/metrics.k8s.io/v1beta1/nodes/node0",
            "creationTimestamp": "2020-02-10T06:38:08Z"
          },
          "timestamp": "2020-02-10T06:38:08Z",
          "window": "1m0s",
          "usage": {
            "cpu": "327m",
            "memory": "2855596Ki"
          }
        }
      ]
    }
---
    kubectl get --raw /apis/metrics.k8s.io/v1beta1/pods | jq .
    {
      "kind": "PodMetricsList",
      "apiVersion": "metrics.k8s.io/v1beta1",
      "metadata": {
        "selfLink": "/apis/metrics.k8s.io/v1beta1/pods"
      },
      "items": []
    }

**Comment by rjswn42** [comment]
After a few tests, 
I figured out experimental/custom-metrics-api/custom-metric-api-configmap.yaml file is the reason for this.
This file uses labels (container_name, pod_name) which are deprecated since version 1.16.
I am able to fix this problem by fixing the file.
