### ISSUE TITLE
Adding Grafana dashboards

### ISSUE THREAD

**Issue by tsloughter** [coreos/kube-prometheus#41]
I'm attempting to import additional grafana dashboards by adding them to the configmap but they are not showing up.

The dashboards work if I import them as files from the grafana UI, the dashboards in question are these two https://github.com/deadtrickster/beam-dashboards

But when I copied their contents as `BEAM.json: |- ...` and `Elli.json: |- ...` to the configmap and apply it they never show up. I know that the watcher is working because in the changes I also included a new datasource in the configmap and that did show up as expected in Grafana.

Is there a difference between the expected input and the files one would upload to grafana?

Any help you can give would be much appreciated, thanks!

**Comment by brancz** [comment]
Dashboards are [expected](https://github.com/coreos/kube-prometheus/blob/dee7f834fba6bd8159526890a8266bf4fae6a70f/grafana-watcher/main.go#L99) to end with `-dashboard.json` to be loaded by the grafana watcher. This is a convention to make our life easier for the time being, however, we have plans to address Grafana workflows in more detail in the future.

**Comment by tsloughter** [comment]
Aah, thanks! Adding `-dashboard.json` fixed it for one of them, `Elli`, but the beam one is still not showing up. I'm checking the grafana logs now to see if it says anything, thanks again.

**Comment by tsloughter** [comment]
Ah, got it! The beam one had `"id": 10` and all the others were `null` I noticed. I changed it to `null` and it was loaded.
