### ISSUE TITLE
prometheus-adapter

### ISSUE THREAD

**Issue by guleng** [coreos/kube-prometheus#423]
**What did you do?**

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

    `Prometheus Operator-v0.3.0`
    

* Kubernetes version information:

    `kubectl version:1.14.1`
    

* Prometheus Operator Logs:
I deployed https://github.com/coreos/kube-prometheus/tree/master/experimental/custom-metrics-api, but I couldn't
```
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1"
Error from server (NotFound): the server could not find the requested resource

root@bs-k8s-master01:~# kubectl  logs -n monitoring prometheus-adapter-655ff5fdc6-kknmc
I1209 11:15:53.613824       1 adapter.go:91] successfully using in-cluster auth
I1209 11:15:53.876413       1 serving.go:273] Generated self-signed cert (/var/run/serving-cert/apiserver.crt, /var/run/serving-cert/apiserver.key)
I1209 11:15:54.224743       1 serve.go:96] Serving securely on [::]:6443
```

I want to use HPA's autoscaling / v2beta2, Do I still deploy https://github.com/DirectXMan12/k8s-prometheus-adapter/tree/master/deploy/manifests?

**Comment by brancz** [comment]
It depends which metrics API you want to use. Kube prometheus by default enables the resource metrics API but not the custom or external metrics API.

**Comment by guleng** [comment]
How to turn it on custom or external metrics API  ，What about normal use of HPA?

**Comment by brancz** [comment]
Check the APIService object. If there’s a problem it should say in the status.

kubectl get apiservice custom.metrics.k8s.io

Auto scaling on resources like CPU or memory is already possible without this though.

**Comment by guleng** [comment]
Can the Prometheus adapter provided by Prometheus operator be deleted? Will it affect Prometheus operator?

Because I deployed directxman12 / k8s Prometheus adapter

**Comment by brancz** [comment]
You can also just modify the one provided by kube-prometheus to use the custom metrics configuration, then you don't have to deploy another one.
