### ISSUE TITLE
WeaveNet Grafana Dashboards and Prometheus Alerts

### ISSUE THREAD

**Issue by alok87** [coreos/kube-prometheus#424]
**What is missing?**
Weave Net grafana dashboards and weave net alert

**Why do we need it?**
Many people spinning up prometheus with weave as the CNI needs weave prometheus monitoring setup and grafana dashboards with alerts configured.

**Environment**
Kubernetes

I have made the Grafana dashboards for weave and also the alerts.
Please let me know if i can integrate it here.

https://stackoverflow.com/questions/60232516/weavenet-grafana-dashboards-and-alerts/60447864#60447864

**Comment by brancz** [comment]
I think a patch to integrate them would be very cool!

**Comment by alok87** [comment]
Can you share an example PR on how to do it..
