### ISSUE TITLE
Kube 1.17.3 no matches for kind "Deployment" in version "apps/v1beta2"

### ISSUE THREAD

**Issue by Stolr** [coreos/kube-prometheus#435]
Hey ,

I followed the steps for the setup 

```
kubectl apply -f manifests/setup/
customresourcedefinition.apiextensions.k8s.io/alertmanagers.monitoring.coreos.com unchanged
customresourcedefinition.apiextensions.k8s.io/prometheuses.monitoring.coreos.com unchanged
customresourcedefinition.apiextensions.k8s.io/prometheusrules.monitoring.coreos.com unchanged
customresourcedefinition.apiextensions.k8s.io/servicemonitors.monitoring.coreos.com unchanged
clusterrole.rbac.authorization.k8s.io/prometheus-operator unchanged
clusterrolebinding.rbac.authorization.k8s.io/prometheus-operator unchanged
service/prometheus-operator unchanged
serviceaccount/prometheus-operator unchanged
error: unable to recognize "manifests/setup/prometheus-operator-deployment.yaml": no matches for kind "Deployment" in version "apps/v1beta2"
```
And in manifests folder

```
unable to recognize "manifests/kube-state-metrics-deployment.yaml": no matches for kind "Deployment" in version "apps/v1beta2"
unable to recognize "manifests/node-exporter-daemonset.yaml": no matches for kind "DaemonSet" in version "apps/v1beta2"
unable to recognize "manifests/prometheus-adapter-deployment.yaml": no matches for kind "Deployment" in version "apps/v1beta2"
```

I think the apps/v1beta2 is not available anymore

I think it is from 1.16 but not sure.

I will of course adapt my files and make it work , but I think there should be some update in the library.

Regards

**Comment by lilic** [comment]
Were you using master or a release branch?

**Comment by lilic** [comment]
As the deployment is using v1 api in master https://github.com/coreos/kube-prometheus/blob/master/manifests/setup/prometheus-operator-deployment.yaml

**Comment by Stolr** [comment]
`jb install github.com/coreos/kube-prometheus/jsonnet/kube-prometheus@release-0.1`

So I should remove the release-0.1 to use master ?

Is master stable enough to use it ?

thanks

**Comment by lilic** [comment]
You can use master, you can also use a release we have a newer release that you can were using, that already uses v1 https://github.com/coreos/kube-prometheus/tree/release-0.4

**Comment by Stolr** [comment]
@lilic  Ok thanks.

I think documentation should be updated then to not use release-0.1

Closing.

**Comment by lilic** [comment]
@Stolr  Yes agreed, just seen that, do you want to create a PR or should I?

**Comment by Stolr** [comment]
Please do it :)
