### ISSUE TITLE
kube-apiserver Grafana dashboard. ETCD cache graphs in Kubernetes >=v1.16

### ISSUE THREAD

**Issue by angelbarrera92** [coreos/kube-prometheus#440]
**What happened?**

The grafana dashboard related to the kube-apiserver has some queries to prometheus (related to etcd) that was deprecated in Kubernetes 1.16.

**Did you expect to see some different?**

Maybe these graphs should be removed.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy this solution in a Kubernetes Cluster > 1.16

**Anything else we need to know?**:

https://github.com/kubernetes/kubernetes/issues/88803#issuecomment-594683394
https://github.com/kubernetes/kubernetes/pull/79520

**Comment by brancz** [comment]
These Grafana dashboards are defined in the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin), and just imported here, please open an issue there :slightly_smiling_face: .
