### ISSUE TITLE
Does not  kube-scheduler and kube-controller-manager provide the metrics on the secure port. ?

### ISSUE THREAD

**Issue by sachinmsft** [coreos/kube-prometheus#443]
I see that https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-serviceMonitorKubeScheduler.yaml scrap config does not provide the option to scrap the kube-scheduler metrics on the secure port. does not kube-scheduler expose the secure metrics port ?

**Comment by brancz** [comment]
They do have secure endpoints, but they didn't use to, so updating this for clusters that now expose the secure endpoints would be fantastic! :)
