### ISSUE TITLE
Node's "free memory" in Grafana actually shows used memory

### ISSUE THREAD

**Issue by urzds** [coreos/kube-prometheus#45]
I installed Prometheus using the `deploy` script from 3a38e173f9a09f27d3a5a59c0cbd59ff8c671ba8.

When I access Grafana at http://MY_NODE:30902/dashboard/db/nodes?var-server=MY_NODE:9100, it displays "Free memory". However, the numbers seemed way off (displaying 5GiB free on a machine that runs almost no services and should have 24GiB of RAM), so I compared with the output of `free -m` on that node. Grafana appears to actually show the "used memory", not "free memory".

Additionally: Maybe adding another graph to the plot, showing "total memory", would help putting the numbers into context.

**Comment by brancz** [comment]
Interesting, thanks for reporting. I will look into it.

**Comment by urzds** [comment]
`/dashboard/db/all-nodes` is also broken.

**Comment by brancz** [comment]
> Very convenient!

That's the idea :slightly_smiling_face: 

I'll make sure to also fix the `All Nodes` dashboard.

**Comment by brancz** [comment]
For reference I opened #47 to also fix the "All Nodes" dashboard. :slightly_smiling_face:

**Comment by brancz** [comment]
The "All Nodes" dashboard fix has also been merged now.
