### ISSUE TITLE
RUNTIME ERROR: Field does not exist: groups

### ISSUE THREAD

**Issue by Icedroid** [coreos/kube-prometheus#451]
$jsonnet -J vendor -m manifests example.jsonnet
`RUNTIME ERROR: Field does not exist: groups         
vendor/kube-prometheus/prometheus/prometheus.libsonnet:67:19-43 object <anonymous>         During manifestation`

**Comment by arianitu** [comment]
@Icedroid We're running into this when we copy and paste the configuration in the documentation, it seems to be when specifying rules: {} and if it's empty this error shows.

Example generating the error:

```
      prometheus+:: {
        names: 'k8s',
        replicas: 1,
        rules: {},              
      },

```

Example fix (remove empty rules):

```
      prometheus+:: {
        names: 'k8s',
        replicas: 1,         
      },

```
