### ISSUE TITLE
Compatibility with Kubernetes Version Needs to be Specified

### ISSUE THREAD

**Issue by CtheSky** [coreos/kube-prometheus#465]
**What is missing?**
A compatibility matrix.

**Why do we need it?**
Helps people know which `kube-prometheus` version to apply depending on their k8s cluster version.

**Environment**

* kube-prometheus version:

    `66c625d0bf`

**Anything else we need to know?**:
On the release page,  I saw:

> Note: This release is more for pinning to a specific commit, master is always stable, and we encourage using master.

`v0.2.0` supports Kubernetes 1.14+ only, but nothing was told about compatibility of `v0.3.0`, so I just deployed  the master branch. And I got alert "KubeStateMetricsListErrors":
```
E0323 06:55:54.144307       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.ValidatingWebhookConfiguration: the server could not find the requested resource
```
From this [issue](https://github.com/kubernetes/kube-state-metrics/issues/1093), `kube-stats-metrics` 1.9.x is not compatible with kubernetes 1.14 any more.

Not sure if I missed something. I tried searching `compatibility` in issue and readme but couldn't find something similar. I think it would be nice if a compatibility table included in readme or explicitly specified on the release page.

**Comment by brancz** [comment]
I think this is reasonable. Generally speaking `master` of kube-prometheus always tries to support the latest stable Kubernetes version.
