### ISSUE TITLE
Rate queries aren't working as expected.

### ISSUE THREAD

**Issue by jason-riddle** [coreos/kube-prometheus#48]
As an example, `node_network_receive_bytes{device!~"lo"}` shows the following.

<img width="877" alt="screen shot 2017-02-22 at 6 27 00 pm" src="https://cloud.githubusercontent.com/assets/2156866/23237710/89f40aaa-f92c-11e6-9ae3-1b86cf2f3650.png">

However, when `rate(node_network_receive_bytes{device!~"lo"}[10m])` is queried, no results are returned.

<img width="430" alt="screen shot 2017-02-22 at 6 27 37 pm" src="https://cloud.githubusercontent.com/assets/2156866/23237738/b142c15a-f92c-11e6-9a97-9e69fa40d2f6.png">

**Comment by brancz** [comment]
Looking at your first graph I'm guessing there are no two points that rate can work with with a `10m` interval.

**Comment by jason-riddle** [comment]
I already tried it with `5m` and `1m`, but it's probably just an issue on my end. Closing.
