### ISSUE TITLE
Prometheus Adapter invalid configuration

### ISSUE THREAD

**Issue by Johannestegner** [coreos/kube-prometheus#486]
**What happened?**

The adapter crashes with the following message:

> unable to load metrics discovery config: unable to load metrics discovery configuration: unable to parse metrics discovery config: not a valid duration string: "5"

**Did you expect to see some different?**

Yes, it should have started!

**How to reproduce it (as minimally and precisely as possible)**:

Run latest version of the manifests.

**Environment**

Kubernetes 1.17.4
Ubuntu 18.04

* Prometheus Operator version:

Git: 115721b

**Anything else we need to know?**:

Pull request incoming in 3... 2...

**Comment by brancz** [comment]
Fixed by #488.
