### ISSUE TITLE
Bring back generate-in-docker make target

### ISSUE THREAD

**Issue by lilic** [coreos/kube-prometheus#498]
On mac OSX the `make generate` also produces an extra files prefixed with 0, e.g. `manifests/setup/prometheus-operator-0prometheusruleCustomResourceDefinition`. This works fine when built within the container, but the problem is my env differs from that, so I need the docker generate for reproducibility. Unless there is a workaround for this, but I haven't found any so far apart from every time removing that file which is tedious.

cc @paulfantom @dgrisonnet 

cc @kakkoyun did you find any solutions for this?

**Comment by paulfantom** [comment]
I see https://github.com/coreos/kube-prometheus/blob/master/manifests/setup/prometheus-operator-0prometheusruleCustomResourceDefinition.yaml as part of the repository, so why not commit?

**Comment by kakkoyun** [comment]
I guess these are the intermittent generates files. Some weird combination of `xargs` and `rm` doesn't work on OS X. I started to use `find` to delete those files. 

e.g `find environments/base/manifests -type f ! -name '*.yaml' -delete`

https://github.com/observatorium/configuration/blob/master/build.sh#L17

**Comment by dgrisonnet** [comment]
This looks intended, those files are even used in the [kustomization.yaml](https://github.com/coreos/kube-prometheus/blob/master/kustomization.yaml#L56-L62).

I have the same behavior on Arch; however, the only CRD files that are generated are prefixed by a 0. Do you see some that are not?

**Comment by lilic** [comment]
No, the file is actually that is generate is just `manifests/setup/prometheus-operator-0prometheusruleCustomResourceDefinition` with no .yaml afterwards, like Kemal said its an intermittent file that is leftover.

**Comment by dgrisonnet** [comment]
Indeed, looks like `xargs` is a bit different on mac OSX.
Instead of bringing back the whole containerization I am fine with @kakkoyun solution. What do you think?

**Comment by lilic** [comment]
Yes that solves the problem for me, my fear is reproducibility for any other env (e.g. windows :D) which is why I like the option to use the generate-in-docker at least, but we can come back to it if that problem happens.

**Comment by dgrisonnet** [comment]
In order to avoid this issue we could run the `build.sh` script inside of a `busybox` image in order to ensure that everybody is using the same binaries.

**Comment by paulfantom** [comment]
Why not add those to `.gitignore` instead of going back to containers?

The idea behind ditching containerized builds was to simplify toolchain and this still stands. If there are intermittent problems with cross-compatibility, let's fix them by either adding exclusions to .gitignore or fixing commands causing problems.
