### ISSUE TITLE
is there email notification and behavior execution in this project?

### ISSUE THREAD

**Issue by KeithTt** [coreos/kube-prometheus#50]
https://prometheus.io/docs/alerting/configuration/#email-receiver-email_config

I need to send email automatically when any service is down and execute a command or a script automatically after that.

**Comment by gianrubio** [comment]
You can configure your alert manager into your configmap. 
```$ kubectl edit configmap -n namespace alertmanager-main```

To run an external command I recommend you to create a web hook notification and run your command inside that.

**Comment by KeithTt** [comment]
how to configure the web hook?

```
kubectl edit configmap alertmanager-main --namespace=monitoring 

# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'webhook'
    receivers:
    - name: 'webhook'
      webhook_configs:
      - url: 'http://alertmanagerwh:30500/'
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"alertmanager-main","creationTimestamp":null},"data":{"alertmanager.yaml":"global:\n  resolve_timeout:
      5m\nroute:\n  group_by: [''job'']\n  group_wait: 30s\n  group_interval: 5m\n  repeat_interval:
      12h\n  receiver: ''webhook''\nreceivers:\n- name: ''webhook''\n  webhook_configs:\n  -
      url: ''http://alertmanagerwh:30500/''"}}'
  creationTimestamp: 2017-02-25T15:02:15Z
  name: alertmanager-main
  namespace: monitoring
  resourceVersion: "6104"
  selfLink: /api/v1/namespaces/monitoring/configmaps/alertmanager-main
  uid: 64ff49e3-fb6b-11e6-a86f-fa163e890e98
```

**Comment by brancz** [comment]
The webhook configured there is just an example, because the Alertmanager needs a valid config to start up. The configuration is intended to be configured to your need, this is not something we can make an assumption for users for as it highly varies between organizations.

The example configuration would send a webhook to `http://alertmanagerwh:30500/` every time it would send out an actual notification (as described [here](https://prometheus.io/docs/alerting/configuration/#webhook-receiver-webhook_config)), but is unlikely to succeed unless that hostname actually resolves and routes to something.

**Comment by KeithTt** [comment]
what is the role of URL `http://172.16.100.215:30903/#/alerts` 
https://github.com/prometheus/prometheus#architecture-overview

can I modify the hostname to a IP address?

how to make it be able to route to something ( I wondered to  what ) ? 
I can see a `receiver: webhook` and two jobs  on the `webui` of alertmanager.
http://172.16.100.215:30903/#/alerts

`job = 'kube-controller-manager'`  alertname = "K8SControllerManagerDown"
` job = 'kube-scheduler'`  alertname = "K8SSchedulerDown"

**Comment by brancz** [comment]
That URL is purely an example to have a valid configuration for the Alertmanager. If you want to make use of the webhook you can change it to whatever you want to point it at, however, if I understand your initial intend, then you want to change that configuration to an email receiver configuration https://prometheus.io/docs/alerting/configuration/#email-receiver-email_config. For example as described in this blog post: https://www.robustperception.io/sending-email-with-the-alertmanager-via-gmail/

**Comment by KeithTt** [comment]
I see... So I need to replace the `webhook` receiver with a email receiver as described in the blog.

Also, I need to execute a command or a script after the email notification, how to `to create a web hook notification and run your command inside that`?

**Comment by brancz** [comment]
That's exactly what you could use the webhook for. You can write a small application that receives the webhook, and then performs some action on that :slightly_smiling_face: .

**Comment by KeithTt** [comment]
I will have a try, thank u.
