### ISSUE TITLE
Error from server (ServiceUnavailable): the server is currently unable to handle the request

### ISSUE THREAD

**Issue by w182757427** [coreos/kube-prometheus#505]
**Focus on the bold parts**
**[root@k8s-master ~]# kubectl get --raw "/apis/metrics.k8s.io/v1beta1"**
Error from server (ServiceUnavailable): the server is currently unable to handle the request
**[root@k8s-master ~]# kubectl get apiservice**
v1beta1.metrics.k8s.io monitoring/prometheus-adapter False (FailedDiscoveryCheck) 44s
**[root@k8s-master ~]# kubectl describe apiservice v1beta1.metrics.k8s.io**
Name: v1beta1.metrics.k8s.io
Namespace:
Labels:
Annotations: kubectl.kubernetes.io/last-applied-configuration:
{“apiVersion”:“apiregistration.k8s.io/v1”,“kind”:“APIService”,“metadata”:{“annotations”:{},“name”:“v1beta1.metrics.k8s.io”},“spec”:{"group…
API Version: apiregistration.k8s.io/v1
Kind: APIService
Metadata:
Creation Timestamp: 2020-04-21T09:30:16Z
Resource Version: 18821900
Self Link: /apis/apiregistration.k8s.io/v1/apiservices/v1beta1.metrics.k8s.io
UID: d0ae5bbf-e63d-4a77-ad7d-7ab45266b1f9
Spec:
Group: metrics.k8s.io
Group Priority Minimum: 100
Insecure Skip TLS Verify: true
Service:
Name: prometheus-adapter
Namespace: monitoring
Port: 443
Version: v1beta1
Version Priority: 100
Status:
Conditions:
Last Transition Time: 2020-04-21T09:30:16Z
**Message: failing or missing response from https://192.168.54.3:6443/apis/metrics.k8s.io/v1beta1: Get https://192.168.54.3:6443/apis/metrics.k8s.io/v1beta1: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)**
Reason: FailedDiscoveryCheck
Status: False
Type: Available
**192.168.54.3:6443 is prometheus-adapter endpoints
So,certificate is issus?**
https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-adapter-deployment.yaml
**There is a:**
volumeMounts:
\- mountPath: /tmp
name: tmpfs
readOnly: false
\- mountPath: /var/run/serving-cert
name: volume-serving-cert
readOnly: false
**It appears to be an automatically generated certificate**
spec:
containers:
\- args:
\- --cert-dir=/var/run/serving-cert
\- --config=/etc/adapter/config.yaml
\- --logtostderr=true
\- --metrics-relist-interval=1m
\- --prometheus-url=http://prometheus-k8s.monitoring.svc:9090/
\- --secure-port=6443
image: quay.io/coreos/k8s-prometheus-adapter-amd64:v0.5.0
…...omit..…
volumes:
\- emptyDir: {}
name: tmpfs
\- emptyDir: {}
name: volume-serving-cert
**But the log seems fine, right
[root@k8s-master ~]# kubectl logs prometheus-adapter-5cd5798d96-59zxf -n monitoring**
I0421 09:26:19.002932       1 adapter.go:93] successfully using in-cluster auth
I0421 09:26:19.661459       1 serving.go:273] Generated self-signed cert (/var/run/serving-cert/apiserver.crt, /var/run/serving-cert/apiserver.key)
I0421 09:26:20.349449       1 serve.go:96] Serving securely on [::]:6443
**So what do we do?**

**Comment by w182757427** [comment]
The problem has been solved

**Comment by ZhiqiangTao** [comment]
@w182757427 how to solve? I also met this problem

**Comment by w182757427** [comment]
> @w182757427 how to solve? I also met this problem

The custom API cannot request an Apiserver, which is resolved by deploying Kubelet on the master and joining the cluster

**Comment by Leozhanggg** [comment]
Thank you very much, I also encountered this problem in Alibaba Cloud environment, and I found that prometheus-adapter needs to be deployed to all master nodes. The following is my modification:

**Comment by Leozhanggg** [comment]
Thank you very much, I also encountered this problem in Alibaba Cloud environment, and I found that prometheus-adapter needs to be deployed to all master nodes. The following is my modification:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-adapter
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      name: prometheus-adapter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: prometheus-adapter
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: node-role.kubernetes.io/master
               operator: Exists
      containers:
......
