### ISSUE TITLE
x-kubernetes-int-or-string CRD field is not support on k8s 1.14

### ISSUE THREAD

**Issue by omerlh** [coreos/kube-prometheus#506]
**What happened?**
The CRD definition generated by the mixin library add this field `x-kubernetes-int-or-string` which is supported only on k8s 1.15 or higher. Worth mentioning that until recently, 1.14 was the latest version supported by EKS. 

The field is ignored by k8s, but when using tools like Argo for deployment, you'll see a constant difference between the desired state and the actual state.

**Did you expect to see some different?**
Option to remove this field.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the CRD definitions on a cluster with version 1.14, notice that the field is removed.

**Comment by lilic** [comment]
What release of kube-prometheus are you using on 1.14 k8s cluster? As we only support release-0.3, is that a problem with that version of the operator as well? https://github.com/coreos/kube-prometheus#kubernetes-compatibility-matrix

**Comment by omerlh** [comment]
I just updated to the latest version - just updated this morning to commit a8b4985de4dc8582dcaf8fd43d6f88a0c08c463d. Look like release 0.3 is pretty up-to-date and contains also the problematic change.

**Comment by dgrisonnet** [comment]
This was introduced by [controller-gen v0.2.3](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.2.3) and we are using v0.2.4 in prometheus-operator. We could fix that on release-0.3 by disabling this field in `kube-prometheus.libsonnet` like it was done for `preserveUnknownField` in #408

**Comment by dgrisonnet** [comment]
Nevermind my previous message release-0.3 is quite different since it is using prometheus-operator v0.34. After looking deeper into release-0.3 I don't find this problematic change.

The commit you updated to is newer than release-0.3 and contains the problematic change. You might want to consider using this commit instead: a98d4be60e1dbc39ce40d7f0532166ba74b23aa2

**Comment by omerlh** [comment]
The problem is I need 876bb9c5a17e980690e58eaa0617451ea8b57c73, this was the only reason for upgrading.

**Comment by lilic** [comment]
> Worth mentioning that until recently, 1.14 was the latest version supported by EKS.

Yeah, sadly know this all too well, in the many projects we have been seeing people complain about 1.14 lack of support. 

> The problem is I need 876bb9c, this was the only reason for upgrading.

You can cherry-pick that fix into previous branches as well.

**Comment by dgrisonnet** [comment]
I believe this issue was fixed by #513 and thus can now be closed, what do you think @omerlh?

**Comment by omerlh** [comment]
Yeah :)
