### ISSUE TITLE
May I use directly kustomize?

### ISSUE THREAD

**Issue by Lawouach** [coreos/kube-prometheus#511]
Hi all,

I'm looking at this repository (thanks for all the effort put into it!) and see you have a kustomization file. I'm fully basing my deployments on Kustomize so this is good in my book :)

However, I'm confused if I should use your kustomization directly? via jsonnet or not all? I didn't see any docs on this aspect so hoped I could get help here.

Thanks,

**Comment by brancz** [comment]
We do generate the setup ready to be used by kustomize via jsonnet, and won't be removing that. That said, if you want to leverage the full effort people have put into this project to adapt monitoring stack as good as possible to specific cluster types (aks, eks, gke, digital ocean, kops, kubespray, kubeadm etc.) then you'll find a much more optimized experience with the jsonnet based approach.

**Comment by metalmatze** [comment]
It seems the question was answered, closing :)
