### ISSUE TITLE
Does it support metrics-server?

### ISSUE THREAD

**Issue by guleng** [coreos/kube-prometheus#529]
After I pull the master branch and deploy the original metrics-server, it is not available. Does it support metrics-server?

**Comment by brancz** [comment]
kube-prometheus ships with the prometheus-adapter which offers the same functionality but doesn't duplicate the work, as prometheus already collects the metrics metrics-server would collect :)

**Comment by cten** [comment]
So should I un-install my instance of metrics-server? Currently the kube-state-metrics is editing the same APIService used by the metrics-server; so it seems only 1 works at a time.

**Comment by brancz** [comment]
Yes we recommend to uninstall metrics-server and use the prometheus-adapter.

**Comment by shinebayar-g** [comment]
Horizontal Pod Autoscaler would work with Prometheus adapter?

**Comment by brancz** [comment]
Yes.
