### ISSUE TITLE
Does node_exporter monitoring work out of the box for you?

### ISSUE THREAD

**Issue by atmosx** [coreos/kube-prometheus#554]
**What did you do?**

Deployed kube-prometheus in AWS EKS cluster. I see `node_exporter` provisioned, however I don't see prometheus collecting data from nodes. I can see the configuration in part about `node_exporter` in prometheus config, but can't see node target in 'targets'.

**Did you expect to see some different?**
I would expect `node_exporter` metrics to be available in prometheus.

**Environment**

AWS EKS 1.16

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.35.1`

* Kubernetes version information:

    `1.16.6`

* Kubernetes cluster kind:

AWS EKS provisioned with terraform terraform (uses the AWS API).

**Anything else we need to know?**:

The `servicemonitor` resource for `node-expoter` seems to be scraping `https` instead of `9100` but setting `targetPort`, updates the prometheus `config` however, no `node_exporter` targets are visible.

I wonder if this works out of the box for others.

**Comment by brancz** [comment]
This works fine for us. Could you check the discovery page in Prometheus and see if there is a node-exporter entry there at all?

**Comment by atmosx** [comment]
> This works fine for us. Could you check the discovery page in Prometheus and see if there is a node-exporter entry there at all?

It's not there. Here is the config I'm using to launch the deployment:

```jsonnet
local kp =
  (import 'kube-prometheus/kube-prometheus.libsonnet') +
  (import 'kube-prometheus/kube-prometheus-eks.libsonnet') +
  // Uncomment the following imports to enable its patches
  // (import 'kube-prometheus/kube-prometheus-anti-affinity.libsonnet') +
  (import 'kube-prometheus/kube-prometheus-managed-cluster.libsonnet') +
  // (import 'kube-prometheus/kube-prometheus-node-ports.libsonnet') +
  // (import 'kube-prometheus/kube-prometheus-static-etcd.libsonnet') +
  // (import 'kube-prometheus/kube-prometheus-thanos-sidecar.libsonnet') +
  // (import 'kube-prometheus/kube-prometheus-custom-metrics.libsonnet') +
  {
    _config+:: {
      namespace: 'monitoring',
      alertmanager+: {
        config: importstr 'config/dm-alertmanager.yaml',
      },
      prometheus+:: {
....
  };

{ ['setup/0namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{
  ['setup/prometheus-operator-' + name]: kp.prometheusOperator[name]
  for name in std.filter((function(name) name != 'serviceMonitor'), std.objectFields(kp.prometheusOperator))
} +
// serviceMonitor is separated so that it can be created after the CRDs are ready
{ 'prometheus-operator-serviceMonitor': kp.prometheusOperator.serviceMonitor } +
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['prometheus-adapter-' + name]: kp.prometheusAdapter[name] for name in std.objectFields(kp.prometheusAdapter) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) }
```

I wonder if am I missing a library or not.

**Comment by atmosx** [comment]
Maybe I need to enable the `kube-prometheus-node-ports.libsonnet` 🤔

**Comment by atmosx** [comment]
The problem was proper prometheus permissions, which come with: 

```
(import 'kube-prometheus/kube-prometheus-all-namespaces.libsonnet') +
````

Closing the issue, ty!
