### ISSUE TITLE
Help please: ran into installation error RUNTIME ERROR: couldn't open import "grafana/grafana.libsonnet": no match locally or in the Jsonnet library paths

### ISSUE THREAD

**Issue by c0ffeec0der** [coreos/kube-prometheus#557]
Problem:

When running bash build.sh example.jsonnet, error occured:

RUNTIME ERROR: couldn't open import "grafana/grafana.libsonnet": no match locally or in the Jsonnet library paths
        vendor/kube-prometheus/kube-prometheus.libsonnet:5:2-36 $
        example.jsonnet:2:4-54  thunk <kp> from <$>
        example.jsonnet:16:86-88
        <std>:1293:24-25        thunk from <function <anonymous>>
        <std>:1293:5-33 function <anonymous>
        example.jsonnet:16:69-104       $

        During evaluation

**What did you do?**
Run the installation steps as per instruction

jb init
jb install github.com/coreos/kube-prometheus/jsonnet/kube-prometheus@release-0.4
jb update
bash build.sh example.jsonnet

**Did you expect to see some different?**
Manifest folder populated with yaml configs

**Environment**
OS: windows using cygwin

**Comment by dgrisonnet** [comment]
The `grafana/grafana.libsonnet` file is coming from a symlink to `github.com/brancz/kubernetes-grafana/grafana`. Your error might have been caused by either jb failing to download kubernetes-grafana or the symlink creation failed during the installation.

Either way you might solve your problem by reinstalling kube-prometheus, but it sure sounds weird that you did not get any errors during the previous steps. While reinstalling kube-prometheus would your mind checking that kubernetes-grafana installation succeeds? You should see the following log line when running jb install/update:
```
GET https://github.com/brancz/kubernetes-grafana/archive/*.tar.gz 200
```
And verify that a symlink gets created under `vendor/grafana` pointing to `github.com/brancz/kubernetes-grafana/grafana`.

**Comment by c0ffeec0der** [comment]
The jb downloaded the zip files. However, there are subsequent command of clean

GET https://github.com/coreos/kube-prometheus/archive/5c63bde4f45c3afe09c9cf0d4dd2651c444c5e5c.tar.gz 200
GET https://github.com/ksonnet/ksonnet-lib/archive/0d2f82676817bbf9e4acf6495b2090205f323b9f.tar.gz 200
GET https://github.com/kubernetes-monitoring/kubernetes-mixin/archive/7bf9a2a321356a7625509fe458132c26b2e33b29.tar.gz 200
GET https://github.com/brancz/kubernetes-grafana/archive/57b4365eacda291b82e0d55ba7eec573a8198dda.tar.gz 200
GET https://github.com/coreos/prometheus-operator/archive/8c85526acc078aa391c24139a8e3ac6b0a5fcabc.tar.gz 200
GET https://github.com/coreos/etcd/archive/09fcf55ca498ade69f4ceb5b3c6afc2930f3621f.tar.gz 200
GET https://github.com/prometheus/prometheus/archive/18d9ebf0ffc26b8bd0e136f552c8e9886d29ade4.tar.gz 200
GET https://github.com/prometheus/node_exporter/archive/02532771213fcb024608043d7b1e514c1a80c2da.tar.gz 200
GET https://github.com/grafana/jsonnet-libs/archive/b9cc0f3529833096c043084c04bc7b3562a134c4.tar.gz 200
GET https://github.com/kubernetes-monitoring/kubernetes-mixin/archive/4626a8d0dd261dbefa91d9d60cf8bc8240bd053f.tar.gz 200
GET https://github.com/grafana/grafonnet-lib/archive/7ab8a79738de007c407b939b35e54e84c213d542.tar.gz 200
GET https://github.com/metalmatze/slo-libsonnet/archive/9baab703bb8a55f990f3b6a74c80987036938f64.tar.gz 200
CLEAN C:\main\repos\Exp-Monitoring\my-kube-prometheus\vendor\github.com\brancz\kubernetes-grafana\grafana
CLEAN C:\main\repos\Exp-Monitoring\my-kube-prometheus\vendor\github.com\coreos\etcd\Documentation
CLEAN C:\main\repos\Exp-Monitoring\my-kube-prometheus\vendor\github.com\coreos\etcd\Documentation\etcd-mixin
CLEAN C:\main\repos\Exp-Monitoring\my-kube-prometheus\vendor\github.com\coreos\prometheus-operator\jsonnet
CLEAN C:\main\repos\Exp-Monitoring\my-kube-prometheus\vendor\github.com\coreos\prometheus-operator\jsonnet\prometheus-operator
CLEAN C:\main\repos\Exp-Monitoring\my-kube-prometheus\vendor\github.com\grafana\grafonnet-lib\grafonnet
CLEAN C:\main\repos\Exp-Monitoring\my-kube-prometheus\vendor\github.com\grafana\jsonnet-libs\grafana-builder
CLEAN C:\main\repos\Exp-Monitoring\my-kube-prometheus\vendor\github.com\metalmatze\slo-libsonnet\slo-libsonnet
CLEAN C:\main\repos\Exp-Monitoring\my-kube-prometheus\vendor\github.com\prometheus\node_exporter\docs
CLEAN C:\main\repos\Exp-Monitoring\my-kube-prometheus\vendor\github.com\prometheus\node_exporter\docs\node-mixin
CLEAN C:\main\repos\Exp-Monitoring\my-kube-prometheus\vendor\github.com\prometheus\node_exporter\docs\node-mixin\alerts
CLEAN C:\main\repos\Exp-Monitoring\my-kube-prometheus\vendor\github.com\prometheus\node_exporter\docs\node-mixin\dashboards
CLEAN C:\main\repos\Exp-Monitoring\my-kube-prometheus\vendor\github.com\prometheus\node_exporter\docs\node-mixin\rules
CLEAN C:\main\repos\Exp-Monitoring\my-kube-prometheus\vendor\github.com\prometheus\prometheus\documentation
CLEAN C:\main\repos\Exp-Monitoring\my-kube-prometheus\vendor\github.com\prometheus\prometheus\documentation\prometheus-mixin

I checked the vendor folder only below folders have contents

vendor\github.com\coreos\kube-prometheus\jsonnet\kube-prometheus
vendor\github.com\ksonnet\ksonnet-lib
vendor\github.com\kubernetes-monitoring\kubernetes-mixin

The symlink are created, but because only above folders have content, only below symlink works

ksonnet
kube-prometheus
kubernetes-mixin
promgrafonnet

The other symlinks don't work. Since the grafana folder is empty, the grafana symlink doesn't work

Could this be an issue in the jb tool that when cleaning the folder?

I checked the jsonnet file

https://github.com/coreos/kube-prometheus/blob/release-0.4/jsonnet/kube-prometheus/jsonnetfile.json

ksonnet and kubernetes-mixin have empty subdir, while others specify subdir, which cause the jb to skip these two in clean command.

However, those with subdir specified was cleaned and because I am in windows the folder notation is '\' different with linux/mac '/'. Jb tool fail to identify the subdir and clean the whole content?

Could this be the issue?

**Comment by c0ffeec0der** [comment]
Create PR for jb

https://github.com/jsonnet-bundler/jsonnet-bundler/pull/114

**Comment by dgrisonnet** [comment]
Yes, it sure sounds like an issue in the way jsonnet bundler handles windows paths.

Thanks for digging this out and opening a follow-up PR in jb :slightly_smiling_face:.

**Comment by c0ffeec0der** [comment]
No probs :)
