### ISSUE TITLE
add custom config with option "additionalScrapeConfigs" but can't create pod whitout error

### ISSUE THREAD

**Issue by degary** [coreos/kube-prometheus#559]
**I add the option "additionalScrapeConfigs:" in manifests/prometheus-prometheus.yaml and apply -f it**

**and i can create prometheus/k8s   but no pods appear in ns/monitoring without error**

**It's normal after deleting the option "additionalScrapeConfigs:"**
`  replicas: 2`
`  additionalScrapeConfigs:      `             
`    name: additional-scrape-configs    `              
`    key: prometheus-additional.yaml`

**Comment by brancz** [comment]
That most likely means your config in the secret is malformed.

**Comment by degary** [comment]
> That most likely means your config in the secret is malformed.

as you said, i rewrite the config file and the problem is solved. thank you for your helping~
