### ISSUE TITLE
Modify storage time

### ISSUE THREAD

**Issue by my1990** [coreos/kube-prometheus#560]
After sts prometheus-k8s is started, --storage.tsdb.retention.time parameter is 24 hours by default. How to modify this parameter? I want to save the data for 15 days
 
![微信图片编辑_20200604090737](https://user-images.githubusercontent.com/16768690/83703900-4b9fb980-a643-11ea-9783-1f8af70258b8.jpg)

**Comment by brancz** [comment]
`.spec.retention` in the Prometheus object.

**Comment by my1990** [comment]
> `.spec.retention` in the Prometheus object.

Thank you very much

**Comment by lign0** [comment]
> `.spec.retention`在普罗米修斯对象中。

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: ops-prod
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: ops-prod
      port: web
  baseImage: 747875099153.dkr.ecr.us-east-1.amazonaws.com/ops-basic/prometheus
  imagePullSecrets:
  - name: registry-secret
  enableFeatures:
    storage.tsdb.min-block-duration: 2h
    storage.tsdb.max-block-duration: 2h


Please take a look at the configuration. I tried to configure it but it doesn't seem to work
