### ISSUE TITLE
Front end presentation questions

### ISSUE THREAD

**Issue by guleng** [coreos/kube-prometheus#565]
My deployed Prometheus version number is: 2.17.2

The problem I found is that I can't see all the rules on the / alerts page. I can only see 202 rules at most. Actually, I have 300 rules

In the / rules page, you can see the actual 300 items. I think this should be a display problem

**Comment by dgrisonnet** [comment]
Could it be because the /alerts endpoint only shows the alerting rules whilst the /rules endpoint shows both the alerting rules and the recording rules?
