### ISSUE TITLE
GCP Cluster requires "Legacy Authorization" to be enabled for prometheus to be able to read pods

### ISSUE THREAD

**Issue by markusjevringsesame** [coreos/kube-prometheus#568]
**What happened?**
I deployed release-0.3 in one cluster (which has "Legacy Authorization" enabled), and it worked perfectly fine. I then deployed it in another cluster (which has "Legacy Authorization" disabled), and prometheus started complaining about not being able to read the pods.

**Did you expect to see some different?**
I would expect that, given all the cluster roles and cluster role bindings in the yamls, that I wouldn't need "legacy authorization" enabled for prometheus to pick up my metrics.

**How to reproduce it (as minimally and precisely as possible)**:
Run a cluster in GKE with "Legacy Authorization" disabled, and release-0.3

**Environment**
GCP

* Prometheus Operator version:
quay.io/coreos/prometheus-operator:v0.34.1

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-gke.15", GitCommit:"9cabee15e0922c3b36724de4866a98f6c2da5e6a", GitTreeState:"clean", BuildDate:"2020-05-01T21:47:04Z", GoVersion:"go1.13.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind:

GKE

* Manifests:
All of them...

* Prometheus Operator Logs:
Lots of things like this. I can provide a whole log if that would help.
```
E0610 14:48:34.731637       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:469: Failed to list *v1.Secret: Get https://10.103.0.1:443/api/v1/secrets?limit=500&resourceVersion=0: dial tcp 10.103.0.1:443: i/o timeout
I0610 14:48:34.784109       1 trace.go:116] Trace[337417971: "Reflector ListAndWatch" name:github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:470 (started: 2020-06-10 14:48:04.783016817 +0000 UTC m=+13516.061339720) (total time: 30.001045447s):
Trace[337417971: [30.001045447s [30.001045447s END
E0610 14:48:34.784147       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:470: Failed to list *v1.StatefulSet: Get https://10.103.0.1:443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0: dial tcp 10.103.0.1:443: i/o timeout
I0610 14:48:34.785129       1 trace.go:116] Trace[1652825821: "Reflector ListAndWatch" name:github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:467 (started: 2020-06-10 14:48:04.784239514 +0000 UTC m=+13516.062562451) (total time: 30.000848873s):
Trace[1652825821: [30.000848873s [30.000848873s END
E0610 14:48:34.785155       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:467: Failed to list *v1.PrometheusRule: Get https://10.103.0.1:443/apis/monitoring.coreos.com/v1/prometheusrules?limit=500&resourceVersion=0: dial tcp 10.103.0.1:443: i/o timeout
I0610 14:48:34.786045       1 trace.go:116] Trace[1302334971: "Reflector ListAndWatch" name:github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:466 (started: 2020-06-10 14:48:04.785401221 +0000 UTC m=+13516.063724415) (total time: 30.000609692s):
Trace[1302334971: [30.000609692s [30.000609692s END
E0610 14:48:34.786092       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:466: Failed to list *v1.PodMonitor: Get https://10.103.0.1:443/apis/monitoring.coreos.com/v1/podmonitors?limit=500&resourceVersion=0: dial tcp 10.103.0.1:443: i/o timeout
I0610 14:48:34.791076       1 trace.go:116] Trace[1148680215: "Reflector ListAndWatch" name:github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:465 (started: 2020-06-10 14:48:04.790487031 +0000 UTC m=+13516.068809974) (total time: 30.000556611s):
Trace[1148680215: [30.000556611s [30.000556611s END
E0610 14:48:34.791122       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:465: Failed to list *v1.ServiceMonitor: Get https://10.103.0.1:443/apis/monitoring.coreos.com/v1/servicemonitors?limit=500&resourceVersion=0: dial tcp 10.103.0.1:443: i/o timeout
I0610 14:48:34.851946       1 trace.go:116] Trace[1027722449: "Reflector ListAndWatch" name:github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:468 (started: 2020-06-10 14:48:04.851087113 +0000 UTC m=+13516.129410023) (total time: 30.000767565s):
Trace[1027722449: [30.000767565s [30.000767565s END
E0610 14:48:34.852144       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:468: Failed to list *v1.ConfigMap: Get https://10.103.0.1:443/api/v1/configmaps?labelSelector=prometheus-name&limit=500&resourceVersion=0: dial tcp 10.103.0.1:443: i/o timeout
I0610 14:48:34.852997       1 trace.go:116] Trace[1621943253: "Reflector ListAndWatch" name:github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:464 (started: 2020-06-10 14:48:04.852275565 +0000 UTC m=+13516.130598462) (total time: 30.000689977s):
Trace[1621943253: [30.000689977s [30.000689977s END
E0610 14:48:34.853021       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:464: Failed to list *v1.Prometheus: Get https://10.103.0.1:443/apis/monitoring.coreos.com/v1/prometheuses?limit=500&resourceVersion=0: dial tcp 10.103.0.1:443: i/o timeout
I0610 14:48:35.265136       1 trace.go:116] Trace[1215380840: "Reflector ListAndWatch" name:github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:242 (started: 2020-06-10 14:48:05.264158739 +0000 UTC m=+13516.542481953) (total time: 30.000933836s):
Trace[1215380840: [30.000933836s [30.000933836s END
E0610 14:48:35.265181       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:242: Failed to list *v1.Alertmanager: Get https://10.103.0.1:443/apis/monitoring.coreos.com/v1/alertmanagers?limit=500&resourceVersion=0: dial tcp 10.103.0.1:443: i/o timeout
I0610 14:48:35.265888       1 trace.go:116] Trace[293879810: "Reflector ListAndWatch" name:github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:243 (started: 2020-06-10 14:48:05.265266937 +0000 UTC m=+13516.543589824) (total time: 30.000570162s):
```
* Prometheus Logs:

Lots and lots of this, over and over again.
```
caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:283: Failed to list *v1.Pod: pods is forbidden ││ : User \"system:serviceaccount:monitoring:prometheus-k8s\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
```

**Anything else we need to know?**:

I also tried with release-0.4, and the problem remains.

**Comment by markusjevringsesame** [comment]
They mention that it's "attribute based access control", and that's it's apparently not the default since kubernetes 1.10, which is ancient: https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster#leave_abac_disabled_default_for_110

**Comment by markusjevringsesame** [comment]
What that *actually* means, I'm not sure. It just seems like it's the authorization method of yesteryear, and since it's not default on any new clusters, is seems reasonable that kube-prometheus, that only supports kuberbetes 1.14 and higher, should work with this default.

**Comment by markusjevringsesame** [comment]
I got it to work by giving the prometheus role all the permissions I could think of. This is of course not ideal, as it should be more nuanced. Also, I did it straight in the generated yamls, which is also not what we want. It does work, however, so I believe an approach similar to this should be used to grant sufficient permissions to the role in question. This was after I upgraded to release-0.4, but I imagine it'll work on 0.3 as well, since manifests/prometheus-clusterRole.yaml is identical in both versions.

Upgrading to release-0.4 also made the prometheus operator stop complaining. Granted, now it complains about using a deprecated field in the alertmanager, but that's probably unrelated.

**Comment by brancz** [comment]
That's odd, we make no use of ABAC at all and never have.

> I got it to work by giving the prometheus role all the permissions I could think of.

Do you have a diff of before/after?

> that only supports kuberbetes 1.14 and higher, should work with this default.

Release 0.4 indeed [does not support 1.14](https://github.com/coreos/kube-prometheus#kubernetes-compatibility-matrix), however, that is not due to permissions so I would still like to figure out what's happening here.

**Comment by markusjevringsesame** [comment]
The release-0.4 test was on a 1.16.8 cluster. Sorry, I should have been more clear.

The change I made to the prometheus-clusterRole.yaml is this.
Before:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
```
After
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  - pods
  - namespaces
  - services
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
  - list
  - watch
```
I eventually put it in my jsonnet file to have it generated for me, but it just mirrored what I hacked into the yaml to get it to work.
I took the permissions I found in prometheus-adapter-clusterRole.yaml and added them to prometheus-clusterRole.yaml. This works on both release 0.3 and 0.4, on both kubernetes 1.14 and 1.16.8.
It's possible I have given it too many permissions, but I wasn't sure exactly what was needed.

**Comment by brancz** [comment]
Hmm .. I don't actually think this has anything to do with the legacy authorization being turned off. Do you happen to have a ServiceMonitor or PodMonitor that selects all namespaces?

**Comment by markusjevringsesame** [comment]
I didn't add one explicitly, so unless it comes with one, I don't. 
I've essentially only done a few things (I can't share the repo, sorry):
* Grafana has a database for editability
* Prometheus has a PVC for metrics storage
* Node exporters run on a different port
* Additional scrape config for prometheus
* More replicas and resources

Everything else is from the examples in the readme.

**Comment by brancz** [comment]
> Additional scrape config for prometheus

Can you elaborate on what you are doing in this additional scrape config?

**Comment by markusjevringsesame** [comment]
I'm doing two things: 
* Doing some label conversion etc to scrape prometheus.io annotations. Basically this: https://github.com/coreos/prometheus-operator/issues/1547
* I'm scraping a /federate endpoint on another prometheus instance, and applying a label to this data.

I don't use any service monitors or anything like that, other than what comes out of the box. All my applications have prometheus.io annotations, so that's what I use to get my application metrics. Everything else is just default.

**Comment by brancz** [comment]
Without seeing the actual config, the first one is probably the thing that needs cluster wide access in your case, as it requires watching all namespaces. The default kube-prometheus setup doesn't do this.

**Comment by markusjevringsesame** [comment]
Are there docs about how to enable this? Watching all the namespaces?

**Comment by brancz** [comment]
There are no dedicated docs I think, but this patch allows you to do it: https://github.com/coreos/kube-prometheus/blob/master/jsonnet/kube-prometheus/kube-prometheus-all-namespaces.libsonnet

**Comment by markusjevringsesame** [comment]
Ok. That's effectively the same thing I ended up doing, but with slightly different syntax. Ok, then at least I know it's not a but, and that it's intended and that there's a work-around. Thanks! =)
