### ISSUE TITLE
Apiserver monitoring indicator is empty 

### ISSUE THREAD

**Issue by ktpktr0** [coreos/kube-prometheus#569]
What's your question
Apiserver monitoring indicator is empty

Environment: OS & Hardware Information

VMware CentOS 7.7，k8s 1.17.3

prometheus error
![image](https://user-images.githubusercontent.com/41657218/84341688-4e1b8980-abd6-11ea-8381-c7b217c030b6.png)

I want to know which SA and clusterrole are used to get apiserver
Because the error notification uses anonymous users

**Comment by brancz** [comment]
The `prometheus` ServiceAccount in the `monitoring` namespace (assuming that's where you deployed it to). I'm fairly certain this is something else though, as we've never seen this in ~4 years.

**Comment by ktpktr0** [comment]
I checked and found that RBAC permissions were correct
![image](https://user-images.githubusercontent.com/41657218/84353972-b1b3b000-abf2-11ea-91e3-d76071e6747e.png)

**Comment by metalmatze** [comment]
Pretty sure this is something misconfigured in your cluster indeed. Closing for now, let us know if you still think it's a problem with kube-prometheus itself.
