### ISSUE TITLE
update to use the latest grafana image 6.7.4 for security patches

### ISSUE THREAD

**Issue by ChrisA-co** [coreos/kube-prometheus#573]
**What is missing?**
Need to use the latest grafana 6 image
https://github.com/coreos/kube-prometheus/blob/master/manifests/grafana-deployment.yaml#L20
main - is 6.6.0
**Why do we need it?**
https://grafana.com/blog/2020/06/03/grafana-6.7.4-and-7.0.2-released-with-important-security-fix/

**Comment by olegmayko** [comment]
if you are familiar with jsonnet, you may configure that on your own  using [instructions](https://github.com/coreos/kube-prometheus#customizing-kube-prometheus). Alternatively, you may achieve the same result with [kustomize](https://github.com/coreos/kube-prometheus/blob/master/kustomization.yaml).
