### ISSUE TITLE
how to configure grafana env

### ISSUE THREAD

**Issue by yangvipguang** [coreos/kube-prometheus#597]
This repository now has the new GitHub Discussions enabled: 
https://github.com/coreos/kube-prometheus/discussions

Please create a new discussion to ask for any kind of support, which is not a Bug or Feature Request.

Thank you for being part of this community!

I want to configure grafana env  。But I have no idea with the format of grafana libjsonnet。Could any one can help me with a example。
![image](https://user-images.githubusercontent.com/11416887/86204945-57779080-bb9b-11ea-9b3d-0f27594e010a.png)

And will  the value of env conflict with the value of config sections。
---

We are still happy to chat with you in the #prometheus-operator channel on Kubernetes Slack!

**Comment by songrijie** [comment]
check [this comment](https://github.com/coreos/kube-prometheus/issues/562#issuecomment-652192186) I made.

**Comment by yangvipguang** [comment]
@songrijie  Thanks a lot. But one question is will the value of env conflict with the value of config sections，and are both of the  equal ?

**Comment by songrijie** [comment]
@yangvipguang  env wins.  

look at [this](https://grafana.com/docs/grafana/latest/administration/configuration/#configure-with-environment-variables)

> All options in the configuration file can be `overridden` using environment variables using the syntax
