### ISSUE TITLE
kube_pod_info cluster label

### ISSUE THREAD

**Issue by bergur88** [coreos/kube-prometheus#603]
Hi
I installed from the helm repo and my setup is missing the cluster label from kube_pod_info.
Can anybody tell me where that is supposed to come from, or what the source of it is  ?
It is not a part of kube-state-metrics according to the [docs](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md)

kube_pod_info{cluster=\"$cluster\"}

**Comment by brancz** [comment]
Cluster is typically something you configure via `external_labels` in Prometheus. This is for when you have multiple Promettheus servers (for example one in each cluster) and you query them centrally, so you can distinguish them.
