### ISSUE TITLE
jimmidyson/configmap-reload pod，localhost After a DNS lookup, the wrong ip was found，120.240..95.33。But the real ip of the pod is 100.111.154.159 

### ISSUE THREAD

**Issue by huangkaiyan10** [coreos/kube-prometheus#611]
2020/07/17 06:19:02 Watching directory: "/etc/prometheus/rules/prometheus-k8s-rulefiles-0"
2020/07/17 06:21:26 config map updated
2020/07/17 06:21:26 performing webhook request (1/1)
2020/07/17 06:21:26 error: Post "http://localhost:9090/-/reload": dial tcp 120.240.95.33:9090: connect: connection refused
2020/07/17 06:21:36 error: Webhook reload retries exhausted

and，how i can change localhost to 127.0.0.1，not use DNS.

**Comment by brancz** [comment]
You can set the `--localhost=127.0.0.1` flag on the Prometheus Operator to achieve this.

**Comment by huangkaiyan10** [comment]
My problem has been solved
![image](https://user-images.githubusercontent.com/5146180/87912905-c6f8e580-caa0-11ea-9296-ec235ccb339c.png)
