### ISSUE TITLE
Prometheus has failed to evaluate 20 rules in the last 5m

### ISSUE THREAD

**Issue by lianfulei** [coreos/kube-prometheus#613]
rule_group=/etc/prometheus/rules/prometheus-po-prometheus-operator-prometheus-rulefiles-0/monitoring-po-prometheus-operator-kubernetes-system-kubelet.yaml;kubernetes-system-kubelet
rule_group=/etc/prometheus/rules/prometheus-po-prometheus-operator-prometheus-rulefiles-0/monitoring-po-prometheus-operator-kubelet.rules.yaml;kubelet.rules

Prometheus monitoring/prometheus-po-prometheus-operator-prometheus-0 has failed to evaluate 30 rules in the last 5m.
Prometheus is failing rule evaluations
why?

**Comment by lianfulei** [comment]
i have save it.

**Comment by acarsercan** [comment]
well done
