### ISSUE TITLE
Compile instructions incorrect

### ISSUE THREAD

**Issue by AdamClarkRock** [coreos/kube-prometheus#71]
I'm trying to compile but the instructions don't seem to work, I'm hoping this is user error on my part:

1) The jb install command  below is incorrect as the repo has moved:
jb install github.com/coreos/prometheus-operator/contrib/kube-prometheus/jsonnet/kube-prometheus

2) I was able to install the dependencies by pointing at the local directory:
jb install github.com/coreos/kube-prometheus/jsonnet/kube-prometheus

3) When running build.sh it fails to resolve the imports as kube-prometheus/kube-prometheus.libsonnet specifies the following that don't exist:
grafana/grafana.libsonnet
prometheus-operator/prometheus-operator.libsonnet
kubernetes-mixin/mixin.libsonnet

**Comment by brancz** [comment]
1 & 2 have been fixed by #73. 

For 3 you probably need to run `jb install` in the root of the repo once.

**Comment by AdamClarkRock** [comment]
Yep that's fixed it, thanks @brancz
