### ISSUE TITLE
Grafana links broken when using subpath

### ISSUE THREAD

**Issue by belcherbrandon** [coreos/kube-prometheus#76]
**What happened?**
Drilldown links on the dashboards are not relative to GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/.  I get a 404 when clicking these links.  They point to http://domain/d/... when they should be pointing to http://domain/grafana/d/...

**Did you expect to see some different?**
Links should not return 404.

**How to reproduce it (as minimally and precisely as possible)**:
Run Grafana under a subpath "/grafana" and behind a reverse proxy.  Navigate to the "Kubernetes / Compute Resources / Namespace" dashboard and click a drilldown pod link in the table.

**Environment**

* Prometheus Operator version: 0.29.0

* Manifests: grafana-dashboardDefinitions.yaml

**Anything else we need to know?**:
Because the page has a <base href="/grafana/"> tag, the dashboard links would work if they didn't start with a slash.  The leading slash makes them relative to the domain instead of the base tag.

**Comment by brancz** [comment]
Yes I agree a relative path would probably work. These dashboards are only coming in here through the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) dependency. Could you open an issue there? Thanks! :slightly_smiling_face:

**Comment by belcherbrandon** [comment]
Thanks @brancz - https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/192

**Comment by brancz** [comment]
If that works, then I'm also happy with that :)

**Comment by andycondon** [comment]
@brancz With https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/192 closed and #265 merged, this issue should be resolved as well.
