### ISSUE TITLE
coredns servicemonitor change

### ISSUE THREAD

**Issue by marklester** [coreos/kube-prometheus#79]
**What happened?**

prometheus doesn't pickup coredns target

**How to reproduce it (as minimally and precisely as possible)**:

install kube-prometheus with the quickstart instructions

**Environment**
* Prometheus Operator version:

quay.io/coreos/prometheus-operator:v0.29.0

* Kubernetes version information:

k8s version: v1.13.5

* Kubernetes cluster kind:

kubespray

* Manifests:

https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-serviceMonitorCoreDNS.yaml#L19

**Anything else we need to know?**:
I believe that line should be:
``` 
k8s-app: coredns
```

**Comment by brancz** [comment]
On most distributions the `Service` selecting CoreDNS pods, is still called `kube-dns` and is also labelled `k8s-app: kube-dns`. If this is different for kubespray, then the [kubespray jsonnet patch](https://github.com/coreos/kube-prometheus/blob/master/jsonnet/kube-prometheus/kube-prometheus-kubespray.libsonnet) should modify that.

**Comment by Alan01252** [comment]
For anyone else looking at this, this is what I've done to generate working configuration with kubespray and kube-prometheus in my jsonnet file. I assume best practice would be to add this to the existing kubespray mixing instead?

```    
     _config+:: {
      namespace: 'monitoring',

      prometheus+:: {
      },

      jobs+: {
        CoreDNS: 'job="coredns"',
      },

    },

    prometheus+:: {

          serviceMonitorCoreDNS+: {
                spec+: {
                  selector: {
                        matchLabels: {
                          'k8s-app': 'coredns',
                        },
                  },
               },
          },


          serviceMonitorKubeScheduler+: {
                spec+: {
                  selector+: {
                        matchLabels: {
                          'k8s-app': 'kube-scheduler',
                        },
                  },
              },
          },

          serviceMonitorKubeControllerManager+: {
                spec+: {
                  selector+: {
                        matchLabels: {
                          'k8s-app': 'kube-controller-manager',
                        },
                  },
             },
          },

          kubeControllerManagerPrometheusDiscoveryService+: {
                spec+: {
                  selector: {
                        'component': 'kube-controller-manager',
                  },
              },
          },

           kubeSchedulerPrometheusDiscoveryService+: {
                spec+: {
                  selector: {
                    'component': 'kube-scheduler',
                  },
              },
          },

    },
`

**Comment by brancz** [comment]
Yes that would be great! Do you want to create the PR for this? :)
