### ISSUE TITLE
Grafana dashboard import via configmap does not work

### ISSUE THREAD

**Issue by occelebi** [coreos/kube-prometheus#81]
I am able to import dashboard directly pasting into Grafana. However it does not work via configMaps.

**What did you do?**
Added dashboards files as ConfigMaps

**Did you expect to see some different?**
I expected dashboard to be imported into Grafana.

* Manifests:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb
  labels:
    grafana_dashboard: "1"
data:
  mongodb.json: |-
    {
      "dashboard": {
        "annotations": {
    }
    trimmed
```

* Grafana Logs:

```
t=2019-04-24T06:57:32+0000 lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name=default file=/tmp/dashboards/mongodb.json error="Dashboard title cannot be empty"
```

**Anything else we need to know?**:
I used [that gist](https://gist.github.com/aranair/bec788df5a9a292f42e088e481b856c6) to produce compatible json for dashboard. But no luck.

**Comment by brancz** [comment]
The gist you linked is for the grafana-watcher, a >2 year old component that has long been deprecated and even removed, as the functionality is now available directly in Grafana. Looking at the other dashboards I think you can just put exactly what you used as input for the script into the ConfigMap.

**Comment by occelebi** [comment]
Thanks for pointing out. It was indentation problem, I guess. It is working as below.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb
  labels:
    grafana_dashboard: "1"
data:
  mongodb.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
```
