### ISSUE TITLE
Pod alertmanager-main keeps restarting because of livenessProbe & readinessProbe failure on aws ec2.

### ISSUE THREAD

**Issue by renaissanceW** [coreos/kube-prometheus#83]
**What happened?**
Pod alertmanager-main keeps restarting because of livenessProbe & readinessProbe failure on aws ec2.
I use 'kubectl exec -n monitoring -it alertmanager-main-0 -- /bin/sh' to get into the Pod
and use 'netstat' to check the port bindings, it seems that on aws ec2, the binding proceeds very slow and then the pod get killed due to livenessProbe & readinessProbe failure.

My question is that, is there any way to customize the 'initialDelaySeconds' of the alertmanager pod? I think maybe enlarge this value can help. 
I find out that the AlertManager is a CRD with its validation of type 'openAPIV3', from this doc(https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/) I can see that 'default' can NOT be set in a CRD, howerver, I failed to find out any place to modify the the 'livenessProbe' or 'readinessProbe' in the whole project folder, and it seems that the 'livenessProbe' or 'readinessProbe' cannot be edited online by 'kubectl edit' command, so I'm totally lost..
Can anyone give me a kindness hand please? So many thanks!

Events:
  Type     Reason     Age                    From                  Message
  ----     ------     ----                   ----                  -------
  Normal   Scheduled  20m                    default-scheduler     Successfully assigned monitoring/alertmanager-main-0 to k8s-test-w3
  Normal   Pulled     20m                    kubelet, k8s-test-w3  Container image "quay.io/prometheus/alertmanager:v0.16.2" already present on machine
  Normal   Created    20m                    kubelet, k8s-test-w3  Created container alertmanager
  Normal   Started    20m                    kubelet, k8s-test-w3  Started container alertmanager
  Normal   Pulled     20m                    kubelet, k8s-test-w3  Container image "quay.io/coreos/configmap-reload:v0.0.1" already present on machine
  Normal   Created    20m                    kubelet, k8s-test-w3  Created container config-reloader
  Normal   Started    20m                    kubelet, k8s-test-w3  Started container config-reloader
  Warning  Unhealthy  19m (x6 over 20m)      kubelet, k8s-test-w3  Liveness probe failed: Get http://10.244.5.70:9093/api/v1/status: dial tcp 10.244.5.70:9093: connect: connection refused
  Warning  Unhealthy  5m36s (x141 over 20m)  kubelet, k8s-test-w3  Readiness probe failed: Get http://10.244.5.70:9093/api/v1/status: dial tcp 10.244.5.70:9093: connect: connection refused
  Warning  BackOff    36s (x34 over 9m2s)    kubelet, k8s-test-w3  Back-off restarting failed container

**Did you expect to see some different?**
no
**How to reproduce it (as minimally and precisely as possible)**:
no
**Environment**
no
* Prometheus Operator version:
no
    `Insert image tag or Git SHA here`
    

* Kubernetes version information:
no
    `kubectl version`
    

* Kubernetes cluster kind:
no
    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:
no
```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:
no
```
Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:
no

**Comment by brancz** [comment]
You can set the `.spec.paused` field to `true`, then you can modify the underlying StatefulSet to try if extending the liveness/readiness probe timeouts. Should this actually help, then we can think of a solution that can be integrated into the Prometheus Operator.

**Comment by renaissanceW** [comment]
Hi brancz,
  Thank you very much for you reply!
  I tried to add .spec.paused to be true in manifests/alertmanager-alertmanager.yaml and then re-deploy
  However, I can NOT find StatefulSet named 'alertmanger' anymore:(
  Is there anything wrong with my operation?

**Comment by brancz** [comment]
You need to first create the object without paused state. Then the Prometheus operator will create the underlying statefulset, then you set the paused state to true, essentially disabling the Prometheus operator from reconciling the object.

**Comment by renaissanceW** [comment]
Hi brancz,
  Thank you so much for your kindness help! According to ur instruction, I indeed succeed to modify the livenessProbe & readinessProbe of alertmanager-main.
  However, I finally found out that aboving two settings are to the root cause. According this article(https://gravitational.com/blog/troubleshooting-kubernetes-networking/) I found that maybe my network-plugin need to utilize UDP traffic, and by default aws will block all UDP traffic. :(
  After letting go all UDP traffic, my problem was resolved, and everything went fine. I think I shall close this issue now(since it is not a issue at all).
  Again, so many thanks for your patient help^.^

**Comment by yangdatianxia** [comment]
Hello, I would like to ask, my alertmanager-main-1 keeps restarting, why? I see you because udp has not been released. I am using an ubuntu22 system, ufw has been turned off, and the two kernel parameters are also invalid. It has been adjusted. How did you troubleshoot the udp problem?
![image](https://github.com/prometheus-operator/kube-prometheus/assets/28724448/218ec6e8-c38a-4db8-be5c-3313d977d875)


![image](https://github.com/prometheus-operator/kube-prometheus/assets/28724448/5852290a-372c-42b0-97e1-325be07829ac)

**Comment by RakeshPuli7337** [comment]
facing same issue readiness connection refuse
