### ISSUE TITLE
node-exporter OOM

### ISSUE THREAD

**Issue by zgfh** [coreos/kube-prometheus#91]
**What happened?**
node-exporter oom many times,should we increase the limit?
https://github.com/coreos/kube-prometheus/blob/master/jsonnet/kube-prometheus/node-exporter/node-exporter.libsonnet#L106

**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
What is the typical usage of this container in your infrastructure? I'd only change this value if we are consistently close to the limit, otherwise I think the safe-guard is not bad.

**Comment by zgfh** [comment]
I deploy prometheus operator to monitor k8s cluster, the node-eporter is one of them ,to monitor host metrics

**Comment by brancz** [comment]
Can you share some data on how much memory the node-exporter uses? You can see that with the cadvisor metrics collected.

**Comment by kskewes** [comment]
For us CPU throttles around 70% of the time and triggers the alert (we adjust it though).

**Comment by zgfh** [comment]
sorry ,my fault, it is limit of container kube-rbac-proxy to too low(40M) https://github.com/coreos/kube-prometheus/blob/master/jsonnet/kube-prometheus/node-exporter/node-exporter.libsonnet#L128

kube-rbac-proxy: (max ~50M)
![image](https://user-images.githubusercontent.com/11729624/57506838-9a3f2f00-732f-11e9-891d-414d011dcde4.png)
node-exporter:  (max ~80M)
![image](https://user-images.githubusercontent.com/11729624/57506939-de323400-732f-11e9-88e8-7922b7e7e90c.png)

**Comment by brancz** [comment]
Yeah looks like it's too small. Would you like to create a PR to bump the limits a bit?
