### ISSUE TITLE
should we auto build manifests

### ISSUE THREAD

**Issue by zgfh** [coreos/kube-prometheus#96]
**What is missing?**
should we auto build manifests? for now is a little difficult for some little change
**Why do we need it?**
may auto build and commit after merge or release?
**Environment**

* kube-prometheus version:

    `Insert Git SHA here`

**Anything else we need to know?**:

**Comment by fritchie** [comment]
fwiw, I make use of the auto built manifests and would prefer they not be removed

**Comment by brancz** [comment]
As the readme says, they are only meant for a quickstart, that's it. You should be generating the manifests with your modifications. We did tag a release yesterday, so you can rely on it a bit better :) 

We may move the generated manifests to be a build artifact, and not check them into the repo anymore. We've discussed this in the past and will likely do this in the future.

**Comment by fritchie** [comment]
understood, thx

**Comment by zgfh** [comment]
Thanks to reply. Expect
