### ISSUE TITLE
Move away from ksonnet-lib since it is deprecated

### ISSUE THREAD

**Issue by wilmardo** [coreos/kube-prometheus#99]
Since ksonnet-lib is deprecated as Heptio is acquired by VMWare:

> Prior to the acquisition, Heptio had been shifting focus and resources away from ksonnet; with the acquisition, we felt it was the right time to rethink our investment in ksonnet. As a result, work on ksonnet will end and the GitHub repositories will be archived. It’s extremely difficult to step back from a project we have worked so hard on, but we’re excited about our new ideas and vision for changing how developers experience the Kubernetes and cloud native ecosystems. The problems that ksonnet aimed to solve are still challenges for Kubernetes users and we will be putting our energy into opportunities to contribute to existing or new projects in this space. [(source)](https://blogs.vmware.com/cloudnative/2019/02/05/welcoming-heptio-open-source-projects-to-vmware/)

CoreOS/RedHat might even acquire or fork the project?

**Comment by metalmatze** [comment]
I have created a PR to add ksonnet.beta.4 to ksonnet-lib that is based on Kubernetes 1.14 and we (as in maintainers of kube-prometheus, Promethues Operator and kubernetes-mixin) have no plans to abandon ksonnet any time soon.
As we just use the ksonnet-lib, which is a subset of the entire ksonnet project, we don't see any reason to move away from it. Plus we know and talk to the former maintainers of ksonnet.
